### ISSUE TITLE
Not able to see datastores

### ISSUE THREAD

**Issue by MikeTomlin19** [josenk/terraform-provider-esxi#1]
When I run terraform apply, I get an error: "Disk Store does not exists :datastore2"

But when I SSH to the esx host and run "ls -d /vmfs/volumes/datastore2"
I get "/vmfs/volumes/datastore2"

`esxi_guest.vmtest: Creating...
  boot_disk_size:                       "" => "<computed>"
  disk_store:                           "" => "datastore2"
  guest_name:                           "" => "vmtest"
  guest_shutdown_timeout:               "" => "20"
  guest_startup_timeout:                "" => "60"
  guestos:                              "" => "<computed>"
  ip_address:                           "" => "<computed>"
  memsize:                              "" => "4096"
  network_interfaces.#:                 "" => "1"
  network_interfaces.0.mac_address:     "" => "<computed>"
  network_interfaces.0.nic_type:        "" => "<computed>"
  network_interfaces.0.virtual_network: "" => "VM Network"
  numvcpus:                             "" => "4"
  ovf_source:                           "" => "/usr/lib/src/github.com/terraform-providers/terraform-provider-esxi/esx-mas-1.ovf"
  power:                                "" => "on"
  resource_pool_name:                   "" => "<computed>"
  virthwver:                            "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* esxi_guest.vmtest: 1 error(s) occurred:

* esxi_guest.vmtest: Disk Store does not exists :datastore2
`

**Comment by MikeTomlin19** [comment]
Here is my main.tf, any help would be greatly appreciated.

`provider "esxi" {
  esxi_hostname      = "<redacted>"
  esxi_hostport      = "22"
  esxi_username      = "root"
  esxi_password      = "<redacted>"
}

resource "esxi_guest" "vmtest" {
  guest_name         = "vmtest"
  disk_store         = "datastore2"
  memsize            = "4096"
  numvcpus           = "4"

  #
  #  Specify an existing guest to clone, an ovf source, or neither to build a bare-metal guest vm.
  #
  # clone_from_vm      = "Templates/centos7"
  ovf_source        = "/usr/lib/src/github.com/terraform-providers/terraform-provider-esxi/esx-mas-1.ovf"

  network_interfaces = [
    {
      virtual_network = "VM Network"
    },
  ]
}
`

**Comment by MikeTomlin19** [comment]
Here is my main.tf file, any help would be greatly appreciated

provider "esxi" {
  esxi_hostname      = "<redacted>"
  esxi_hostport      = "22"
  esxi_username      = "root"
  esxi_password      = "<redacted>"
}

resource "esxi_guest" "vmtest" {
  guest_name         = "vmtest"
  disk_store         = "datastore2"
  memsize            = "4096"
  numvcpus           = "4"
  ovf_source        = "/usr/lib/src/github.com/terraform-providers/terraform-provider-esxi/esx-mas-1.ovf"

  network_interfaces = [
    {
      virtual_network = "VM Network"
    },
  ]
}

**Comment by josenk** [comment]
I have a feeling the Datastores needs to be rescaned....  I've seen this issue a few times with the Vagrant-esxi plugin also.

>https://github.com/josenk/vagrant-vmware-esxi/issues/41
>https://github.com/josenk/vagrant-vmware-esxi/issues/49

Please try this command and let me know if it solves your issue.
```
# esxcli storage filesystem rescan
```


   It seems that this problem crops up a little more often then I imagined.   Doing a rescan before each operation could make deploy time much longer, so I didn't rescan by default.   I'll try to come out with a long term solution.

**Comment by MikeTomlin19** [comment]
Thank you, @josenk.  Unfortunately, I'm still seeing the same issue.  I tried the command you provided, as well as the reboot suggested in the vagrant issues.

If it helps, I am using ESXi 6.7

Thanks for creating this tool, I think it will be very useful.

**Comment by ktmorgan** [comment]
@MikeTomlin19 I think the error is misleading. Are you using version 1.0.0? By default ESXi 6.7 (and possibly other versions, unconfirmed) does not have PasswordAuthentication enabled. You can either add that line (or set to yes instead of no), then restart the ssh daemon, or from what I've read the latest release of this plugin adds support for the default authentication method that ESXi uses by default. I would definitely go this route if possible.

What the line in your ESXi host' /etc/ssh/sshd_config should look like:
```
PasswordAuthentication yes
```

Also, you can check to see which authentication methods your ESXi server has enabled by using the -v flag when connecting to the host using ssh. You should see a line like this (I've added password auth to my ESXi host).
```
debug1: Authentications that can continue: publickey,password,keyboard-interactive
```

**Comment by josenk** [comment]
Try using the latest plugin...   I changed the password authentication method, now verifies esxi host connectivity and improved the Data Stores validation.  

   You could also enable Terraform debug to get more details of the problem...

**Comment by MikeTomlin19** [comment]
@ktmorgan That did it! Thank you. I enabled password authentication in /etc/ssh/sshd_config.


@josenk I will also update the plugin. Thanks again.

**Comment by cpbann21** [comment]
@josenk I successfully deployed a VM using ubuntu trusty ovf file but don't know the username and password to login to it.
Kindly help me with the username and password variable which I can add to the terraform code.

**Comment by josenk** [comment]
I don't know what your password is...  You should check with the person that created that Ubuntu image.
