### ISSUE TITLE
Terraform packet.net

### ISSUE THREAD

**Issue by tnrwil** [josenk/terraform-provider-esxi#10]
I am trying to do a terraform plan on my esxi server. This does not contain a Vsphere Server. Here is the following error I get after I have compiled the provider:
Error: Error running plan: 1 error(s) occurred:

* provider.esxi: Failed to connect to esxi host: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

**Comment by berney** [comment]
Is SSH enabled on the ESXi server? Can you SSH in from shell?

**Comment by tnrwil** [comment]
Yes I can. The packet.net sets there servers is via ssh keys to get to host.

**Comment by tnrwil** [comment]
So in packet.net you upload you sshkeys. Once uploaded you can use the ipaddress or hostname to connect to the server from your local box. From the web console I can login as well but that is a different user name and password. So I made sure the root user can login via ssh. I will spin up another one and we can test it out

**Comment by tnrwil** [comment]
Okay so without the key you can't hit the command line terminal. I tried from another box that I didn't exchange keys with

**Comment by tnrwil** [comment]
Yeppers all of that was done. Ssh was turned on the hyper visor and port 22 is open and says server is running on the same port. No go. I checked all of that before I posted

**Comment by berney** [comment]
You need to be able to login to ESXi over SSH with a password. Try doing that using standard `ssh` in shell (e.g. bash) terminal. It should be asking for a password and not using an SSH pubkey/certificate.

**Comment by tnrwil** [comment]
i moved to another datacenter and it works on that one. I will try packet again
