### ISSUE TITLE
OVF missing allowExtraConfig option

### ISSUE THREAD

**Issue by erickfear** [josenk/terraform-provider-esxi#102]
Terraform plan trows an error :
esxi_guest.vm: Creating...

Error: There was an ovftool Error:
C:\demo\1234\terraform>ovftool --acceptAllEulas --noSSLVerify --X:useMacNaming=false  -dm=thin --name="DISIISC55x" --overwrite -ds="datastore1"  "vi://root:1234@192.168.0.200/iis_template" "vi://root:1234@192.168.0.200/"
Opening VI source: vi://root@192.168.0.200:443/iis_template
Error: ExtraConfig options exists in source (use --allowExtraConfig option to allow this).
Completed with errors

exit status 1

  on main.tf line 16, in resource "esxi_guest" "vm":
  16: resource "esxi_guest" "vm" {

On Windows adding parameter "allowExtraConfig"  to ovf_cmd.bat station is created.

Can I add this switch somewhere in config ?

files :
main.tf
terraform {
  required_version = ">= 0.12"
}
provider "esxi" {
  esxi_hostname      = "192.168.0.200"
  esxi_hostport      = "22"
  esxi_username      = "root"
  esxi_password      = "1234"
}
resource "esxi_guest" "vm" {
  guest_name         = "DISIISC55x"
  disk_store         = "datastore1"
memsize  = "2049"
numvcpus = 2
power = "on"
  clone_from_vm      = "iis_template"
  	network_interfaces {
	virtual_network = "servers"

  }
}

Variables.tf
variable "esxi_hostname" {
  default = "192.168.0.200"
}
variable "esxi_hostport" {
  default = "22"
}
variable "esxi_username" {
  default = "root"
}
variable "esxi_password" {
  default = "1234"
}
variable "virtual_network" {
  default = "servers"
}
variable "esxi_network_interface_type" {
  default = "vmxnet3"
}
variable "disk_store" {
  default = "datastore1"
}
variable "esxi_default_disk_size" {
  default = "45"
}
variable "ovf_file" {
   default = "iis_template.ovf"
}
variable "vm_hostname" {
  default = "vmtest06"
}
variable "vm_name" {
    description = "vsphere server password for the environment"
  default = "DISIISC51x"
}
variable "guest_startup_timeout" {
  default = "180"
}

**Comment by josenk** [comment]
I'm not able to re-create your problem.  Can you please describe the issue in more detail.   Even better, please fill out the "Bug Report" template.

**Comment by erickfear** [comment]
C:\demo\aaa\terraform>terraform.exe apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # esxi_guest.vm will be created
  + resource "esxi_guest" "vm" {
      + boot_disk_size         = (known after apply)
      + clone_from_vm          = "iis_template"
      + disk_store             = "datastore1"
      + guest_name             = "DISIISC55x"
      + guest_shutdown_timeout = (known after apply)
      + guest_startup_timeout  = (known after apply)
      + guestos                = (known after apply)
      + id                     = (known after apply)
      + ip_address             = (known after apply)
      + memsize                = "2049"
      + notes                  = (known after apply)
      + numvcpus               = "2"
      + ovf_properties_timer   = (known after apply)
      + power                  = "on"
      + resource_pool_name     = (known after apply)
      + virthwver              = (known after apply)

      + network_interfaces {
          + mac_address     = (known after apply)
          + nic_type        = (known after apply)
          + virtual_network = "servers"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

esxi_guest.vm: Creating...

Error: There was an ovftool Error:
C:\demo\aaa\terraform>ovftool --acceptAllEulas --noSSLVerify --X:useMacNaming=false  -dm=thin --name="DISIISC55x" --overwrite -ds="datastore1"  "vi://root:1234%21@192.168.0.200/iis_template" "vi://root:1234%21@192.168.0.200/"
Opening VI source: vi://root@192.168.0.200:443/iis_template
Error: ExtraConfig options exists in source (use --allowExtraConfig option to allow this).
Completed with errors

exit status 1


  on main.tf line 16, in resource "esxi_guest" "vm":
  16: resource "esxi_guest" "vm" {


File called : ovf_cmd.bat is created. Files mail. and variables are above. terraform and plugins are located in same folder, ovftool have path defined (it's called without issue) ony thing that seems to be missing is this setting for ovftool.

So my question is, can I add this ( --allowExtraConfig) somewhere to my terrraforms variables so ovf_cmd.bat would include it while beeing created ?

**Comment by josenk** [comment]
No, you cannot add any extra options in the tf files.

**Comment by josenk** [comment]
BTW:  The --allowExtraConfig will automatically be added when you are using an (ova or ovf ) ovf_source AND you have ovf_properties set.   You do not have either of these set in your example. (you are using clone_from_vm).

> https://github.com/josenk/terraform-provider-esxi/blob/master/esxi/guest-create.go#L229-L240

**Comment by erickfear** [comment]
Consider this issue closed. This "bug" was in OFVTOOl in ver 4.2 after upgrading it to latest 4.3, problem was solved.
