### ISSUE TITLE
Error: Failed to instantiate provider "esxi" to obtain schema: fork/exec /root/.terraform.d/plugins/terraform-provider-esxi_v1.6.4: exec format error

### ISSUE THREAD

**Issue by ankycooper** [josenk/terraform-provider-esxi#106]
I'm able to use the provider on a windows PC however cant use it on Linux and I get the error

Error: Failed to instantiate provider "esxi" to obtain schema: fork/exec /root/.terraform.d/plugins/terraform-provider-esxi_v1.6.4: exec format error

Logs:
`/tf # TF_LOG=DEBUG terraform init
2020/04/16 14:27:46 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/04/16 14:27:46 [INFO] Terraform version: 0.12.24  
2020/04/16 14:27:46 [INFO] Go runtime version: go1.12.13
2020/04/16 14:27:46 [INFO] CLI args: []string{"/bin/terraform", "init"}
2020/04/16 14:27:46 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2020/04/16 14:27:46 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/04/16 14:27:46 [DEBUG] checking for credentials in "/root/.terraform.d/plugins"
2020/04/16 14:27:46 [INFO] CLI command args: []string{"init"}
2020/04/16 14:27:46 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----

Initializing the backend...
2020/04/16 14:27:46 [DEBUG] New state was assigned lineage "adbe2342-a58f-12e2-fa1e-4ffe2e9ae0a4"
2020/04/16 14:27:46 [DEBUG] checking for provider in "."
2020/04/16 14:27:46 [DEBUG] checking for provider in "/bin"
2020/04/16 14:27:46 [DEBUG] checking for provider in "/root/.terraform.d/plugins"
2020/04/16 14:27:46 [DEBUG] found provider "terraform-provider-esxi_v1.6.4"
2020/04/16 14:27:46 [WARN] found legacy provider "terraform-provider-kubeadm"
2020/04/16 14:27:46 [WARN] found legacy provider "terraform-provider-kubectl_linux_amd64"
2020/04/16 14:27:46 [DEBUG] found valid plugin: "kubeadm", "0.0.0", "/root/.terraform.d/plugins/terraform-provider-kubeadm"
2020/04/16 14:27:46 [DEBUG] found valid plugin: "kubectl_linux_amd64", "0.0.0", "/root/.terraform.d/plugins/terraform-provider-kubectl_linux_amd64"
2020/04/16 14:27:46 [DEBUG] found valid plugin: "esxi", "1.6.4", "/root/.terraform.d/plugins/terraform-provider-esxi_v1.6.4"
2020/04/16 14:27:46 [DEBUG] checking for provisioner in "."
2020/04/16 14:27:46 [DEBUG] checking for provisioner in "/bin"
2020/04/16 14:27:46 [DEBUG] checking for provisioner in "/root/.terraform.d/plugins"
2020/04/16 14:27:46 [WARN] found legacy provisioner "terraform-provisioner-kubeadm"
2020/04/16 14:27:46 [INFO] Failed to read plugin lock file .terraform/plugins/linux_amd64/lock.json: open .terraform/plugins/linux_amd64/lock.json: no such file or directory
2020/04/16 14:27:46 [DEBUG] checking for provider in "."
2020/04/16 14:27:46 [DEBUG] checking for provider in "/bin"
2020/04/16 14:27:46 [DEBUG] checking for provider in "/root/.terraform.d/plugins"
2020/04/16 14:27:46 [DEBUG] found provider "terraform-provider-esxi_v1.6.4"
2020/04/16 14:27:46 [WARN] found legacy provider "terraform-provider-kubeadm"
2020/04/16 14:27:46 [WARN] found legacy provider "terraform-provider-kubectl_linux_amd64"
2020/04/16 14:27:46 [DEBUG] found valid plugin: "esxi", "1.6.4", "/root/.terraform.d/plugins/terraform-provider-esxi_v1.6.4"
2020/04/16 14:27:46 [DEBUG] found valid plugin: "kubeadm", "0.0.0", "/root/.terraform.d/plugins/terraform-provider-kubeadm"
2020/04/16 14:27:46 [DEBUG] found valid plugin: "kubectl_linux_amd64", "0.0.0", "/root/.terraform.d/plugins/terraform-provider-kubectl_linux_amd64"
2020/04/16 14:27:46 [DEBUG] plugin requirements: "esxi"=""
2020/04/16 14:27:46 [DEBUG] checking for provider in "."

Initializing provider plugins...
2020/04/16 14:27:46 [DEBUG] checking for provider in "/bin"
2020/04/16 14:27:46 [DEBUG] checking for provider in "/root/.terraform.d/plugins"
2020/04/16 14:27:46 [DEBUG] found provider "terraform-provider-esxi_v1.6.4"
2020/04/16 14:27:46 [WARN] found legacy provider "terraform-provider-kubeadm"
2020/04/16 14:27:46 [WARN] found legacy provider "terraform-provider-kubectl_linux_amd64"
2020/04/16 14:27:46 [DEBUG] found valid plugin: "esxi", "1.6.4", "/root/.terraform.d/plugins/terraform-provider-esxi_v1.6.4"
2020/04/16 14:27:46 [DEBUG] found valid plugin: "kubeadm", "0.0.0", "/root/.terraform.d/plugins/terraform-provider-kubeadm"

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
2020/04/16 14:27:46 [DEBUG] found valid plugin: "kubectl_linux_amd64", "0.0.0", "/root/.terraform.d/plugins/terraform-provider-kubectl_linux_amd64"
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.esxi: version = "~> 1.6"

2020/04/16 14:27:46 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
/tf # 
/tf # TF_LOG=DEBUG terraform initplan
2020/04/16 14:27:58 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/04/16 14:27:58 [INFO] Terraform version: 0.12.24  
2020/04/16 14:27:58 [INFO] Go runtime version: go1.12.13
2020/04/16 14:27:58 [INFO] CLI args: []string{"/bin/terraform", "plan"}
2020/04/16 14:27:58 [DEBUG] Attempting to open CLI config file: /root/.terraformrc
2020/04/16 14:27:58 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/04/16 14:27:58 [DEBUG] checking for credentials in "/root/.terraform.d/plugins"
2020/04/16 14:27:58 [INFO] CLI command args: []string{"plan"}
2020/04/16 14:27:58 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/04/16 14:27:58 [DEBUG] New state was assigned lineage "e1c5ee51-9096-d3c2-ed2d-a4808f8da5d2"
2020/04/16 14:27:58 [DEBUG] checking for provider in "."
2020/04/16 14:27:58 [DEBUG] checking for provider in "/bin"
2020/04/16 14:27:58 [DEBUG] checking for provider in ".terraform/plugins/linux_amd64"
2020/04/16 14:27:58 [DEBUG] checking for provider in "/root/.terraform.d/plugins"
2020/04/16 14:27:58 [DEBUG] found provider "terraform-provider-esxi_v1.6.4"
2020/04/16 14:27:58 [WARN] found legacy provider "terraform-provider-kubeadm"
2020/04/16 14:27:58 [WARN] found legacy provider "terraform-provider-kubectl_linux_amd64"
2020/04/16 14:27:58 [DEBUG] found valid plugin: "kubeadm", "0.0.0", "/root/.terraform.d/plugins/terraform-provider-kubeadm"
2020/04/16 14:27:58 [DEBUG] found valid plugin: "kubectl_linux_amd64", "0.0.0", "/root/.terraform.d/plugins/terraform-provider-kubectl_linux_amd64"
2020/04/16 14:27:58 [DEBUG] found valid plugin: "esxi", "1.6.4", "/root/.terraform.d/plugins/terraform-provider-esxi_v1.6.4"
2020/04/16 14:27:58 [DEBUG] checking for provisioner in "."
2020/04/16 14:27:58 [DEBUG] checking for provisioner in "/bin"
2020/04/16 14:27:58 [DEBUG] checking for provisioner in ".terraform/plugins/linux_amd64"
2020/04/16 14:27:58 [DEBUG] checking for provisioner in "/root/.terraform.d/plugins"
2020/04/16 14:27:58 [WARN] found legacy provisioner "terraform-provisioner-kubeadm"
2020/04/16 14:27:58 [INFO] backend/local: starting Plan operation
2020-04-16T14:27:58.957Z [INFO]  plugin: configuring client automatic mTLS
2020-04-16T14:27:58.987Z [DEBUG] plugin: starting plugin: path=/root/.terraform.d/plugins/terraform-provider-esxi_v1.6.4 args=[/root/.terraform.d/plugins/terraform-provider-esxi_v1.6.4]

Error: Failed to instantiate provider "esxi" to obtain schema: fork/exec /root/.terraform.d/plugins/terraform-provider-esxi_v1.6.4: exec format error
`

**Comment by josenk** [comment]
I googled "golang exec format error". Found this.
>https://stackoverflow.com/questions/36198418/golang-cannot-execute-binary-file-exec-format-error

What Linux distro are you using?   Are you using 32 or 64bit?

**Comment by ankycooper** [comment]
I have tried it on Ubuntu 18.04 64 bit vm and my custom docker image based on alpine.

**Comment by ankycooper** [comment]
Compiled it and it works like a charm (available on docker-hub: docker pull ankycooper/tf-kubeadm-esxi:latest) Looks like there is some issue on the release 1.6.4 (https://github.com/josenk/terraform-provider-esxi/releases/download/v1.6.4/terraform-provider-esxi_v1.6.4)

**Comment by josenk** [comment]
Thanks for the update.

**Comment by lamtt77** [comment]
Hi, I got the same error using the default build README github instruction on MacOS 10.13.6.  However, this has worked after I changed the build into:

CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -a -ldflags '-w -extldflags "-static"' -o terraform-provider-esxi_`cat version`
