### ISSUE TITLE
Possible to store ESXi hostname in terraform state file?

### ISSUE THREAD

**Issue by iPhrankie** [josenk/terraform-provider-esxi#108]
Would it be possible to store the esxi hostname within the Terraform state file?

I would like to target an ESXi host based on a variable, which might be a random_shuffle. I believe the state file would need the ESXI hostname so Terraform knows which host the VM resides on?

Or is there a different approach?

Thanks!

**Comment by josenk** [comment]
If the entire deployment will be on the same ESXi host, then you can use workspaces.  But I don't think you can random shuffle the hosts...   You would have to experiment a bit with it.  Workspaces is a great way to separate code from variables.
* https://www.terraform.io/docs/commands/workspace/index.html
* https://www.terraform.io/docs/cloud/workspaces/index.html


If the deployment has resources deployed to multiple esxi hosts as the same time.  I know of two different ways to do it...    This is a similar type of problem if you are trying to deploy to AWS in multiple regions.    You can google many examples how people solve that problem.
* Configure provider aliases.
  * https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances
* Using Modules. 
  * https://www.terraform.io/docs/modules/index.html

**Comment by iPhrankie** [comment]
Thank you for your response and help.

I've been deploying VMs against a single esxi host via automation. This esxi host is getting full. I need to target another esxi host for new VMs. However, I still need to target either host if an automated task comes in that references an existing VM.

I could pass the "host" in the terraform command line? If I do this, will it get stored in the state file? I inspected the existing state file and it contains a lot of info, but it's missing the esxi host info. I think if it contained the host info where the VM is located then I would be all set because I already reference the state files in the automation.

This is my variables.tf file.

variable "host" {
    type = string
    default = "172.0.0.1"
}

**Comment by josenk** [comment]
Your issue has nothing to do with this plugin.   You may want to read the terraform documentation for other solutions if my suggestions didn't work for you..
