### ISSUE TITLE
Unable to clone VM when powered on 

### ISSUE THREAD

**Issue by vikas-nyt** [josenk/terraform-provider-esxi#109]
Hi Josenk ,

Is there any way to clone VM when it is powered on .I am able to clone when it is powered off .
I am getting below error when i try to clone while powered on 

Error: There was an ovftool Error: Opening VI source: vi://root@10.7.47.15:443/vmstatic02
Error: vim.fault.TaskInProgress
Completed with errors

exit status 1

I am using the code which you have posted .Please advice if any work around to clone while it is powered on.

**Comment by josenk** [comment]
That is a limitation of ovftool.   You cannot clone while it's powered on.
