### ISSUE TITLE
SSH Session Reuse

### ISSUE THREAD

**Issue by berney** [josenk/terraform-provider-esxi#11]
Thanks for the great tool. I am finding it often plans to re-create VMs that already exist, that have no issues, or will not plan to destroy a VM that it should destroy. I think the crux of this is that the tool makes many SSH connections to run commands, each one is a new session, a new connection, and it mostly works, but sometimes due to the hammering of SSH connections, a connection will be refused. In this case a simple error string is returned and the callers don't distinguish this error from command output. So believing that the resource has the wrong setting or that the resource doesn't exist it wants to create it, or not destroy it.

I'm not very good at golang yet. I tried modifying the source to re-use sessions to find that the SSH library doesn't work like that. I tried to cache clients and to implement a retry mechanism but that resulted in terraform crashing due to a segfault - probably due to my changes in the plugin.

Could you make SSH reuse connections/channels, or similar - similar to the ssh cli equivalent of `-o ControlMaster=auto -o ControlPersist=60s`. Ideally with configurable values. Could you also add a retry mechanism to running the ssh commands.

**Comment by josenk** [comment]
Interesting theory about the ssh connections, but I have not seen that issue at all.  Do you have a poor connection to your esxi (VPN, etc???)   I would expect that re-running the plan would have different results each time if that were the case.

 Terraform keeps track of what's built and not-built by their IDs.  I use the vmid as the unique identifier.   If something needs to be re-built, it will tell you why.   Post some examples.

Sorry, but I won't be doing any code change to use a single ssh session.  Having sessions open for long periods of time can cause timeouts.   If you have poor connections, your problems would be even worse! 
>https://github.com/josenk/vagrant-vmware-esxi/issues/8

**Comment by berney** [comment]
I'm connected via a LAN (gigabit Ethernet). When I do `TF_LOG=DEBUG` I can see the ssh session being rejected sometimes. Also I have seen some attributes with `Failed to ssh to esxi host` as their value, causing Terraform to plan to recreate the resource to fix the current / desired value mismatch.

The more VMs you have the defined in terraform the more SSH connections that are made. If you are just creating one VM it might not be spamming SSH enough to see the issue. I have ~15 VMs defined and approximately every second run will have a plan that is wrong, if I reject the plan and re-run it I'm have a chance to get a correct plan.

**Comment by josenk** [comment]
As a work-around try using the terraform command line arg "-parallelism=n"   n=10 by default.  Try a lower value.
>https://www.terraform.io/docs/commands/apply.html

I'll check if I can re-create your problem...

**Comment by berney** [comment]
Thanks, I'll try this and see if it helps work-around or reduce the problem.

**Comment by berney** [comment]
Thanks for this, I did some testing and the changes appear to have resolved the issue.
