### ISSUE TITLE
ovftool fails when ESXi management is accessed via bastion server

### ISSUE THREAD

**Issue by twss** [josenk/terraform-provider-esxi#111]
I have an SSH bastion setup with `LocalForwarding` as follows:

- 2222 > mgmt_ip:22
- 9443 > mgmt_ip:443

SSH on 2222 is fine, however `ovftool` assumes the connection is being established over port 443, and as a result fails:

```
The manifest validates
Error: Internal error: Failed to connect to remote host [127.0.0.1] due to [No version for VMODL calls to <cs p:00007fac651bb210, TCP:127.0.0.1:443>]
Completed with errors

exit status 1
```

**Comment by josenk** [comment]
Thanks for the PR.   I published V1.7.0 with your changes!
>https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.7.0
