### ISSUE TITLE
Publish provider for use in Terraform 0.13

### ISSUE THREAD

**Issue by paultyng** [josenk/terraform-provider-esxi#113]
👋 Hi, I'm on the Terraform Providers team at HashiCorp. With the [release of the Terraform 0.13 beta](https://discuss.hashicorp.com/t/terraform-0-13-beta-released/9555), users can now download and install community providers from the registry. We are inviting provider authors (especially those for popular community providers) to publish their providers in a closed beta.

To get invited to the closed beta, please email terraform-registry-beta@hashicorp.com. We need:

- A list of GitHub usernames to add to the beta (you and any team members who will publish)
- List of provider repositories you plan to publish
- A GPG public key in ASCII-armor format, which you will be using to sign your provider releases

You can use one key for all of your providers, or separate keys if you prefer. If you are publishing from an organization, this key or keys will be associated with that namespace. Once in the beta, you can manage personal keys in the UI as well.

**Comment by josenk** [comment]
I added this provider to the terraform registry...  
>https://registry.terraform.io/providers/josenk/esxi
