### ISSUE TITLE
Error: Failed to instantiate provider "esxi" to obtain schema

### ISSUE THREAD

**Issue by hisasai** [josenk/terraform-provider-esxi#115]
**Describe the bug**
I ran into the following error when I did "terraform plan/apply" even using the sample, "01 Simple Guest".
   "Error: Failed to instantiate provider "esxi" to obtain schema: fork/exec /usr/local/bin/terraform-provider-esxi_v1.7.0: exec format error"
The only change I made is "esci_hostname" in variable.tf.

**To Reproduce**
1. terraform init
2. terraform validate/plan/apply
     See error 'Error: Failed to instantiate provider "esxi" to obtain schema: fork/exec /usr/local/bin/terraform-provider-esxi_v1.7.0: exec format error'

**Expected behavior**
The provider "esxi" should be instantiated.

**Terraform files**
~/go/src/github.com/josenk/terraform-provider-esxi/examples/01 Simple Guest\ $ terraform init

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.esxi: version = "~> 1.7"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
~/go/src/github.com/josenk/terraform-provider-esxi/examples/01 Simple Guest\ $
~/go/src/github.com/josenk/terraform-provider-esxi/examples/01 Simple Guest\ $ terraform plan
var.esxi_password
  Enter a value: xxxxxx

Error: Failed to instantiate provider "esxi" to obtain schema: fork/exec /usr/local/bin/terraform-provider-esxi_v1.7.0: exec format error

~/go/src/github.com/josenk/terraform-provider-esxi/examples/01 Simple Guest\ $
~/go/src/github.com/josenk/terraform-provider-esxi/examples/01 Simple Guest\ $ cat main.tf
#########################################
#  ESXI Provider host/login details
#########################################
#
#   Use of variables here to hide/move the variables to a separate file
#
provider "esxi" {
  esxi_hostname = var.esxi_hostname
  esxi_hostport = var.esxi_hostport
  esxi_hostssl  = var.exsi_hostssl
  esxi_username = var.esxi_username
  esxi_password = var.esxi_password
}

#########################################
#  ESXI Guest resource
#########################################
#
#  This Guest VM is "bare-metal".   It will be powered on by default
#  by terraform, but it will not boot to any OS.   It will however attempt
#  to network boot.
#
resource "esxi_guest" "vmtest01" {
  guest_name = "vmtest01" # Required, Specify the Guest Name
  disk_store = "DS_001"   # Required, Specify an existing Disk Store
  network_interfaces {
    virtual_network = "VM Network" # Required for each network interface, Specify the Virtual Network name.
  }
}

~/go/src/github.com/josenk/terraform-provider-esxi/examples/01 Simple Guest\ $
~/go/src/github.com/josenk/terraform-provider-esxi/examples/01 Simple Guest\ $ terraform -v
Terraform v0.12.28
+ provider.esxi v1.7.0
~/go/src/github.com/josenk/terraform-provider-esxi/examples/01 Simple Guest\ $

**Desktop (please complete the following information):**
 - OS: macOS Mojave ver10.14.16
 - Terraform Version: v0.12.28
 - Ovftool Version: VMware ovftool 4.4.0 (build-15722219)
 - provider.esxi v1.7.0

**Additional context**
 - Add any other context about the problem here.
 - Enable terraform debugging, then re-run commands that produced the error:
    - export TF_LOG=DEBUG
    - Initially this may not be required, however, be prepared to upload debug information IF REQUESTED.

**Comment by josenk** [comment]
'exec format error' is your error.   Seems like you downloaded the wrong version...   You can Google that error message for additional details.

https://github.com/josenk/terraform-provider-esxi/issues/71

**Comment by hisasai** [comment]
Thank you. 
I have it worked with the MAC version of provider.esxi v1.7.0.
