### ISSUE TITLE
Using the provider within Windows 10 WSL on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by sukster** [josenk/terraform-provider-esxi#116]
Hello,

I am sure that I this is not yet supported but I tried to build the provider on Windows 10 WSL version 1 using the Ubuntu 20.04 LTS. Everything was built smoothly however the only issue is when I run terraform apply with the provider, the provisioning process is extremely slow. Is anybody aware of any workaround? I am primarily a Windows user and I would like to be able to use WSL with Terraform.

Thank you, Ludek

**Comment by josenk** [comment]
'provisioning process is extremely slow'  You will need to provide some more context...    How long does it take to provision the exact same resources using your WSL build vs other builds (Windows, Linux or Mac)? 

BTW:  I'm not 100% sure because I personally haven't used WSL, but shouldn't you be able to just use the Linux executable provided?

>https://github.com/josenk/terraform-provider-esxi/releases

**Comment by sukster** [comment]
Thanks for your reply! In the mean time, I was able to resolve the issue. I was using Ubuntu 20.04 LTS app within WSL which apparently still has some bugs. After running the provider under Ubuntu "18.04" LTS app, the Terraform works at expected speeds. And yes, I also used the released provider Linux binary from the link above so there is no need to build the provider.
This way, let me thank you a lot for such a very helpful product! I am using it with clong's DetectionLab.

**Comment by josenk** [comment]
Thanks for the update...  I'm happy to hear you got it working and that using the supplied linux binary works on WSL.  That can be useful for someone in the future..  Thanks @clong.  He has made some great suggestions and contributes to my projects.
