### ISSUE TITLE
Mount CDROM ISO image

### ISSUE THREAD

**Issue by berney** [josenk/terraform-provider-esxi#13]
How to create a VM with an ISO mounted in the CDROM?

I would like to use cloud-init to set the hostname and other initialisation tasks. One way to inject the userdata is to use an CDROM image (ISO). However, it looks like the esxi_guest resource doesn't support such a feature.

I'm not sure if `ovftool` supports it changing the mounted ISO.

I am wanting to clone an existing VM several times and provide different ISOs to each, which a templated config - e.g hostname: guest0, guest1, guest2.

An alternative is use VMware GuestInfo and which can be used as cloud-init userdata source with this https://github.com/akutz/cloud-init-vmware-guestinfo

**Comment by josenk** [comment]
Currently there is no support for CDROM.    It's a bit complex, so I wanted to see if there was any real demand for it before doing all the work.  So far, you are the first :)

I'll look into it further.

**Comment by berney** [comment]
What about being able to set guestinfo?

**Comment by josenk** [comment]
I did a bit of research...   Looks like guestinfo might be a good way to go.   It will be easier for you to put userdata in guestinfo vs a CDROM...   

Sorry, I'm a little over-loaded at work these days, so it might take a few weeks to implement this.

**Comment by silasb** [comment]
Hi @berney I have a branch where guestinfo works.  I'm using it to standup CoreOS instances.

**Comment by berney** [comment]
Great @silasb, this should be useful for cloud-init userdata from guestinfo. Your fork seems to have diverged quite a lot from upstream. I think part of it might be from merging vs rebasing.

**Comment by silasb** [comment]
Yep, I'm slowly sorting it out.  I'll try to squeeze in some time this
afternoon to work on it.
—Silas

**Comment by silasb** [comment]
Been super busy.  Haven't forgotten about this.  I'm aiming for some time later this week to rebase some of my code on master.

**Comment by josenk** [comment]
A solution in V1.4.0 works with cloud-init / GuestInfo.  Please verify and update this thread with your results.
>https://github.com/josenk/terraform-provider-esxi/releases/tag/1.4.0

**Comment by berney** [comment]
I have tested CoreOS and this is working well, thanks for the example configs. I will test other OSes, if I notice any issues I'll raise them.

My original rationale for mounting CD-ROMs was cloud-init userdata, now that guestinfo is working my original need has been satisfied, so I am closing this issue.
