### ISSUE TITLE
Feature Request - Add key values to VMX file

### ISSUE THREAD

**Issue by sukster** [josenk/terraform-provider-esxi#134]
Hello Josenk,

Thank you for creating this free provider for those of us who are using a free version of ESXi. Recently, I wanted to set some options in the VMX file and realized that only Packer vmware.iso builder can do this using the "vmx_data" option (see here: https://www.packer.io/docs/builders/vmware/iso). But for specific reasons, I need this set in a later stage during provisioning by Terraform or Ansible. Ansible modules seem to work only with vCenter so no free option there. 

Has anybody else requested this before and have you considered this as a feature request or am I the only one?

Thanks, Ludek

**Comment by josenk** [comment]
The problem with this request is that it's virtually impossible to fully implement in Terrafom...   Terrafom keeps track of the state.  It must be able to read the state (read the vmx file in this case) and compare it to it's known state to determine if it needs to make any changes.  

 Using something like vmx_data will be impossible to read or import. 

Btw, I implemented something like this in my vagrant plugin.

**Comment by sukster** [comment]
Thank you for explaining this to me. Makes total sense. I will look for alternatives. You may close this issue.
