### ISSUE TITLE
`examples-0.13/06 OVF Properties` does NOT work

### ISSUE THREAD

**Issue by soulmachine** [josenk/terraform-provider-esxi#136]
This is probably a question rather than a bug report.

I used the example `examples-0.13/06 OVF Properties` to create a virtual machine on my ESXi host based on the image <https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.ova>, the VM was created successfully, but I couldn't login with the password `Passw0rd1`.

Any suggestions? Thanks

**Comment by josenk** [comment]
Sorry, no idea.  You might want to take a look at some logs.

**Comment by soulmachine** [comment]
I turned to [govc](https://github.com/vmware/govmomi/tree/master/govc) which set the ssh public key successfully
