### ISSUE TITLE
Add support for using SSH keys

### ISSUE THREAD

**Issue by cyberdood** [josenk/terraform-provider-esxi#145]
Unless I missed something, I didn't see any support for using ssh keys vs user name and password for the esxi provider credentials. is there a way to do this or can it be added?

**Comment by josenk** [comment]
There is no support for ssh keys.   Ovftool doesn't support ssh keys, so this plugin can not support ssh keys.

**Comment by cyberdood** [comment]
Oh, I see. Thanks.
