### ISSUE TITLE
win10: terraform-provider-esxi_v1.8.2.exe plugin crashed

### ISSUE THREAD

**Issue by juhoarvid** [josenk/terraform-provider-esxi#147]
date;terraform apply;date
Wed, Sep  1, 2021 10:43:51 AM

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # esxi_guest.tf_local_http_share will be created
  + resource "esxi_guest" "tf_local_http_share" {
      + boot_disk_size         = (known after apply)
      + boot_disk_type         = "thin"
      + disk_store             = "dc"
      + guest_name             = "tf_local_http_share"
      + guest_shutdown_timeout = (known after apply)
      + guest_startup_timeout  = (known after apply)
      + guestos                = (known after apply)
      + id                     = (known after apply)
      + ip_address             = (known after apply)
      + memsize                = (known after apply)
      + notes                  = (known after apply)
      + numvcpus               = (known after apply)
      + ovf_properties_timer   = (known after apply)
      + ovf_source             = "http://localhost:8888/testi.ova"
      + power                  = (known after apply)
      + resource_pool_name     = "/"
      + virthwver              = (known after apply)

      + network_interfaces {
          + mac_address     = (known after apply)
          + nic_type        = (known after apply)
          + virtual_network = "Testing-network"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

esxi_guest.tf_local_http_share: Creating...
╷
│ Error: Plugin did not respond
│
│   with esxi_guest.tf_local_http_share,
│   on josenk.tf line 30, in resource "esxi_guest" "tf_local_http_share":
│   30: resource "esxi_guest" "tf_local_http_share" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-esxi_v1.8.2.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0xdd8955]

goroutine 53 [running]:
github.com/josenk/terraform-provider-esxi/esxi.guestCREATE(0xc000070410, 0xc000032780, 0xc, 0xc000032760, 0xe, 0xc00018e2d0, 0x2a, 0x1949d2f, 0x1, 0x0, ...)
        github.com/josenk/terraform-provider-esxi/esxi/guest-create.go:201 +0x25a5
github.com/josenk/terraform-provider-esxi/esxi.resourceGUESTCreate(0xc000422d20, 0xeed320, 0xc000070410, 0x2, 0x19f7f00)
        github.com/josenk/terraform-provider-esxi/esxi/resource_guest.go:394 +0x1836
github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc000226a00, 0xc0005fab90, 0xc000509500, 0xeed320, 0xc000070410, 0xefe101, 0xc000600988, 0xc0001a6930)
        github.com/hashicorp/terraform@v0.12.2/helper/schema/resource.go:286 +0x36c
github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc000226d00, 0xc00057b8d0, 0xc0005fab90, 0xc000509500, 0xc00019d708, 0xc000006730, 0xf00240)
        github.com/hashicorp/terraform@v0.12.2/helper/schema/provider.go:285 +0xa0
github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc0002024d0, 0x129f820, 0xc000196240, 0xc0005fcd20, 0xc0002024d0, 0xc000196240, 0xc0006b9a48)
        github.com/hashicorp/terraform@v0.12.2/helper/plugin/grpc_provider.go:851 +0x899
github.com/hashicorp/terraform/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x10100a0, 0xc0002024d0, 0x129f820, 0xc000196240, 0xc0005fa8c0, 0x0, 0x129f820, 0xc000196240, 0xc0000f5800, 0x3c8)
        github.com/hashicorp/terraform@v0.12.2/internal/tfplugin5/tfplugin5.pb.go:3217 +0x21e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000084c00, 0x12ab500, 0xc000085500, 0xc000167700, 0xc000400bd0, 0x19bc0a0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.18.0/server.go:966 +0x471
google.golang.org/grpc.(*Server).handleStream(0xc000084c00, 0x12ab500, 0xc000085500, 0xc000167700, 0x0)
        google.golang.org/grpc@v1.18.0/server.go:1245 +0xca5
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000218150, 0xc000084c00, 0x12ab500, 0xc000085500, 0xc000167700)
        google.golang.org/grpc@v1.18.0/server.go:685 +0xa8
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.18.0/server.go:683 +0xa8

Error: The terraform-provider-esxi_v1.8.2.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Wed, Sep  1, 2021 10:44:08 AM
>

**Comment by josenk** [comment]
unable to re-produce the problem.
