### ISSUE TITLE
defer file.Close() after return?

### ISSUE THREAD

**Issue by rgl** [josenk/terraform-provider-esxi#150]
The following code seems to have a stray `defer file.Close()` after a `return`:

https://github.com/josenk/terraform-provider-esxi/blob/e91bddc8900573f6881e3553e1faeff8010f2edc/esxi/guest-create.go#L270-L271

Is that really the intent?

**Comment by josenk** [comment]
Yea, that seems wrong...    I'll take a look at it when I get a chance.   A bit crazy at work these days.

**Comment by josenk** [comment]
Fixed in V1.9.1
