### ISSUE TITLE
version in tag v1.9.1 contains wrong version string

### ISSUE THREAD

**Issue by bish0polis** [josenk/terraform-provider-esxi#160]
**Describe the bug**
the stated version in [/version in v1.9.1.tar.gz is '](https://github.com/josenk/terraform-provider-esxi/blob/v1.9.1/version) is 'v1.9.0', which causes problems during build.

This mis-match started in https://github.com/josenk/terraform-provider-esxi/blob/v1.8.0/version

https://github.com/josenk/terraform-provider-esxi/blob/v1.7.2/version has it right.

**Comment by josenk** [comment]
Thanks for letting me know!  I'll look into it.

**Comment by josenk** [comment]
I just released v1.10.0.   Looks like it got pushed correctly this time.

**Comment by bish0polis** [comment]
It seems to have rolled into an installable package just fine, too, where it previously blew up.  Thanks for keeping this ticket open.
