### ISSUE TITLE
Portgroup Security Policy not inheriting from vSwitch 

### ISSUE THREAD

**Issue by kurotorakun** [josenk/terraform-provider-esxi#161]
**Describe the bug**
After 1.9.1 release, Portgroup Security policy is not inherited from vSwitch.
In the pull, #153 , that triggers the release seems that the security policy can be configured, but there is no documentation for that.

**To Reproduce**
1.- create a vSwitch resource that modifies default params (for example, promiscuous = "true")
2.- create a Portgroup resource
3.- deploy infra (terraform apply)
4.- once completed, vSwitch security param is set as written. Portgroup security policy is set to default.

**Expected behavior**
In 1.8.3 version the portgroups were inheriting settings from vSwitch. 

**Additional context**
From #153 seems that the Portgroup security policy can be configured, but no documentation is registered.

**Comment by kurotorakun** [comment]
Dear josenk,

I opened as an issue, but if the documentation is written, it just an improve of the Portgroup resource creation.

Thanks in advance,
K.

**Comment by josenk** [comment]
Yes, I can confirm this problem...   I will fix it in the next release.

**Comment by josenk** [comment]
Fixed in https://github.com/josenk/terraform-provider-esxi/tree/v1.10.0

**Comment by kurotorakun** [comment]
Dear @josenk ,

Thanks for the feedback.
I can confirm that version 1.10.0 solves the issue with portgroup inheritance.

Issue can be closed.

Thanks,
K.
