### ISSUE TITLE
Specifying the IP_Address and Hostname on a Vm

### ISSUE THREAD

**Issue by mikeelnite** [josenk/terraform-provider-esxi#163]
![Captura de ecrã 2021-12-17 153709](https://user-images.githubusercontent.com/96304253/146569538-d7aca7fb-f1ab-471d-ac7d-be935742e3ac.png)

![Captura de ecrã 2021-12-17 153806](https://user-images.githubusercontent.com/96304253/146569617-48e73f42-fd93-41da-af71-6bef2af87979.png)

How I can specify the IP_Address and Hostname using the terraform-provider-esxi plugin??

**Comment by josenk** [comment]
You cannot.  This is a provider, not a provioner.   See the readme.
