### ISSUE TITLE
clone_from_vm: Failed to open file stream: ISO?

### ISSUE THREAD

**Issue by nb25186** [josenk/terraform-provider-esxi#175]
Hi,
I am trying to clone an existing VM with clone_from_vm and the process proceeds very slowly (like 45 minutes for a 25GB vmdk) but at a certain point it fails:

│ Error: There was an ovftool Error:
│ C:\Users\myself\automation3>ovftool --acceptAllEulas --noSSLVerify --X:useMacNaming=false  -dm=thin --name="mpn-clone" --overwrite -ds="datastore1"  "vi://root:Password%21@10.1.0.26:443/mpn-base" "vi://root:Password%21@10.1.0.26:443//"
│ Opening VI source: vi://root@10.1.0.26:443/mpn-base
│ Opening VI target: vi://root@10.1.0.26:443//
│ Deploying to VI: vi://root@10.1.0.26:443//
Transfer Failed
│ Error: Failed to open file stream: https://10.1.0.26:443/ha-nfc/5287229d-a464-81a0-cbc1-46c1ee661500/mpn-base-0.iso
│ Completed with errors
│
│ exit status 1
│
│   with esxi_guest.mpn-clone,
│   on main.tf line 26, in resource "esxi_guest" "mpn-clone":
│   26: resource "esxi_guest" "mpn-clone" {
 

Now, there's no ISO in the datastore mpn-base folder. Is this like a misleading message?

Thanks

**Comment by josenk** [comment]
Does that source vm have an iso assigned to the cdrom?

**Comment by nb25186** [comment]
> Does that source vm have an iso assigned to the cdrom?

That was it! Thank you, sincerely!!!!
