### ISSUE TITLE
Cloning/Copying VM from one ESXI to another ESXI

### ISSUE THREAD

**Issue by cyberdood** [josenk/terraform-provider-esxi#177]
Can functionality be added to Clone/Copy a VM from one ESXI host to another? Seems like the ovftool supports it. 

https://4sysops.com/archives/copy-vmware-vms-between-esxi-hosts-using-the-ovf-tool/

**Comment by josenk** [comment]
I don't have another esxi to test, but I believe it's already supported...   ovf_source begins with vi:// in in the code.  
> https://github.com/josenk/terraform-provider-esxi/blob/master/esxi/guest-create.go#L217

Have you tried using ovf_source?

**Comment by josenk** [comment]
Do you still need help with this?

**Comment by josenk** [comment]
abandoned
