### ISSUE TITLE
ovftool Error in Windows

### ISSUE THREAD

**Issue by damok6** [josenk/terraform-provider-esxi#18]
Hi,

The terraform plugin is working for basic planning and applying in Windows. It is, however, having issues when and ovf_source is specified. When an ovf_source is specified in Windows the following error occurs while applying a plan:

```
Error: Error applying plan:

1 error(s) occurred:

* esxi_guest.vmtest: 1 error(s) occurred:

* esxi_guest.vmtest: There was an ovftool Error:
exec: "/bin/bash": file does not exist
```

It appears to be an issue with how the ovftool is being called in windows, as the ovftool works when called in the command line. Also I get a different error when I specify an invalid ovf_source path.

Thanks,
Damian.

P.S. great work on this plugin!

**Comment by josenk** [comment]
Clever solution to your problem...  Use the Vagrant Plugin to use the Terraform plugin...   :-)

However, I figured out the Windows exec part.   There is a few things I need to do a little different for it to work.  There will be an update soon that will include this fix...    No need for the PR.  Thanks.

**Comment by josenk** [comment]
Should be fixed:
>https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.2.2

**Comment by josenk** [comment]
I believe it just needs to be in your PATH...  So your process should work fine.  I'll reword the readme in the next release.
