### ISSUE TITLE
MAC conflict

### ISSUE THREAD

**Issue by tosqui17** [josenk/terraform-provider-esxi#184]
**Describe the bug**
After creating a ubuntu 22.04.1 image via packer, esxi automatically assigns a mac address to my network card (e.g. 00:0c:29:e7:c9:ec). Later, if I try to apply it in the network_interfaces settings in main.tf, machine does not turn on.

 Error: Failed to power on.
│
│   with esxi_guest.Ubuntu22041,
│   on main.tf line 9, in resource "esxi_guest" "Ubuntu22041":
│    9:   resource "esxi_guest" "Ubuntu22041" {

If I do it manually via esxi dashboard, it says:
Impermissible static Ethernet address: '00:0c:29:e7:c9:ec'. It conflicts with VMware reserved MACs.

**To Reproduce**
1. terraform apply

**Terraform files**

**main.tf**

provider "esxi" {
        esxi_hostname = var.esxi_hostname
        esxi_hostport = var.esxi_hostport
        esxi_username = var.esxi_username
        esxi_password = var.esxi_password
}

  resource "esxi_guest" "Ubuntu22041" {
        guest_name = "Ubuntu22041"
        boot_disk_type = "thin"
        disk_store = "datastore1"
        memsize = "4096"
        numvcpus = "2"
        boot_disk_size = "20"
        power = "on"
        network_interfaces {
                virtual_network = "VM Network"
                nic_type = "vmxnet3"
                mac_address = "00:0c:29:e7:c9:ec"
                }

        }

**terraform apply**

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # esxi_guest.Ubuntu22041 will be created
  + resource "esxi_guest" "Ubuntu22041" {
      + boot_disk_size         = "20"
      + boot_disk_type         = "thin"
      + boot_firmware          = "bios"
      + disk_store             = "datastore1"
      + guest_name             = "Ubuntu22041"
      + guest_shutdown_timeout = (known after apply)
      + guest_startup_timeout  = (known after apply)
      + guestos                = (known after apply)
      + id                     = (known after apply)
      + ip_address             = (known after apply)
      + memsize                = "4096"
      + notes                  = (known after apply)
      + numvcpus               = "2"
      + ovf_properties_timer   = (known after apply)
      + power                  = "on"
      + resource_pool_name     = "/"
      + virthwver              = (known after apply)

      + network_interfaces {
          + mac_address     = "00:0c:29:e7:c9:ec"
          + nic_type        = "vmxnet3"
          + virtual_network = "VM Network"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

**Comment by josenk** [comment]
You need to follow the rules of mac address assignment.   This problem is not related to the provider or terraform.   This restriction is from vmware.
