### ISSUE TITLE
warning about legacy plugin SDK

### ISSUE THREAD

**Issue by djdanielsson** [josenk/terraform-provider-esxi#185]
**Describe the bug**
I am was having issues with ova files so just to try and get a baseline I tried using your examples which errored for me, I changed the output to debug to try and figure out what the issue is (still looking into it) but noticed a warning saying

2022-09-20T20:15:53.841-0500 [WARN]  Provider "registry.terraform.io/josenk/esxi" produced an invalid plan for esxi_guest.vmtest, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .boot_disk_type: planned value cty.StringVal("thin") for a non-computed attribute
      - .resource_pool_name: planned value cty.StringVal("/") for a non-computed attribute
      - .boot_firmware: planned value cty.StringVal("bios") for a non-computed attribute

**To Reproduce**
1. clone the repo and init the "06 OVF Properties" example folder turn on debug logs with 'export TF_LOG ="debug"'
2. update variables file to point to your ESXi server and your password. change to URL OVA file and then try to apply the plan.

**Expected behavior**
producing up to date plan

**Terraform files**
Used the ones from the examples folder

**Desktop (please complete the following information):**
 - OS: RHEL8
 - Terraform Version: Terraform v1.2.9
 - Ovftool Version: VMware ovftool 4.4.1 (build-16812187)
 - This Plugin Version provider registry.terraform.io/josenk/esxi v1.10.2

**Additional context**
none

**Comment by djdanielsson** [comment]
quick note, while filling this out I figured out the issue with ova files I was having, I was missing a lib that was required for the ovftool to work. so that is working now, this is just a note about the legacy plugin SDK warning, I have not looked into if Hashi will remove the legacy support in the future but I would expect it is coming.

**Comment by josenk** [comment]
Thanks for the comments...   I will investigate the legacy support.
