### ISSUE TITLE
Newbie - clone_from_vm or guestinfo doc

### ISSUE THREAD

**Issue by stikmou007** [josenk/terraform-provider-esxi#200]
Hello, i'm trying to use terraform with an esxi free edition ^^
I have installed our provider en reach to create one VM but without OS.
I try to understand how to do for installing any OS and I see the cd_rom option is not avaible.
I have see clone_from_vm or guestinfo but I don't understand how it's works.

I have followed this tuto https://williamlam.com/2012/05/how-to-deploy-ovfova-in-esxi-shell.html for installing ovftool but is no working.

If someone have any tips to help me it's sounds cool

P./ excuse me if this is not the best way and for my english ^^

**Comment by josenk** [comment]
You'll need to provide more details.

**Comment by stikmou007** [comment]
Juste, like a newbee ^^, I'm have wonder how to create a VM with an OS (like Ubuntu) installed.
But since my post, I have reache how using "clone_from_vm" and how to install ovftools.

So on esxi the best way is to create a "vm template"  that we can use with ovftools to create a new VM with OS done.
If there is an other way, don't have find it.

I'm going to close this "issue"
