### ISSUE TITLE
Support for arbitrary ISO file installation to create an Android VM

### ISSUE THREAD

**Issue by MassiLucio** [josenk/terraform-provider-esxi#201]
I would like to use the terraform-vsphere module to create an ESXi virtual machine running the Android operating system. I was wondering if the module supports using an arbitrary ISO file for OS installation.

In particular, I have an .iso file of Android that I would like to use to create the virtual machine. Is it possible to pass the URL path of this ISO file as a "image_url" parameter to specify the OS to install?

If support is not yet present, what is the best way to contribute to adding it to the module? I would like to be able to easily create ESXi virtual machines with any ISO I want.

Thank you for your support and consideration of this request! I look forward to starting to create Android virtual machines on ESXi with terraform-vsphere.

**Comment by josenk** [comment]
ER here: https://github.com/josenk/terraform-provider-esxi/issues/95
