### ISSUE TITLE
│ Error: No network mapping specified. OVF networks:   Bridged  NAT. Target networks:   VM Network  VM Network2

### ISSUE THREAD

**Issue by raoua97** [josenk/terraform-provider-esxi#206]
│ Error: No network mapping specified. OVF networks:   Bridged  NAT. Target networks:   VM Network  VM Network2

**Comment by josenk** [comment]
You'll need to provide more details if you want support.  What are you trying to do?  How do you re-produce the problem?

**Comment by EXIST696** [comment]
Hello raoua97,
I am beginner in esxi too tho, but i think this error is caused either by :
-you dont already have a network (port name) called "VM Network VM Network2"
- or maybe use custom network (vmnet1 for exp) in esxi network settings
I dont know if thats working or actually respond ur problem , as i told you am just a begginer.

Regards.

**Comment by josenk** [comment]
You can create a vm network using this provider, or you can specify one that already exists.   If you are not sure how to do those things, you should try doing a few things manually first before trying to automate them with terraform.
