### ISSUE TITLE
ReadMe identifies a breaking change at version 1.9.0

### ISSUE THREAD

**Issue by ajn142** [josenk/terraform-provider-esxi#207]
**Describe the bug**
ReadMe file identifies that 1.9.0 changes the default hwversion value from 8 to 13, and this may be a breaking change for older versions of ESXi. It doesn't identify what versions of ESXi this may break.

**To Reproduce**
1. Read the ReadMe.md file for this repository, specifically the line brought up by https://github.com/josenk/terraform-provider-esxi/#:~:text=hwversion

**Expected behavior**
I thought I'd know what versions this would be a breaking change for.

**Terraform files**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**

**Comment by ajn142** [comment]
I found the vmWare documentation here. Looks like this is a breaking change for versions of ESXi older than 6.5.

https://kb.vmware.com/s/article/1003746

I'll put in a pull request to clarify the ReadMe

**Comment by josenk** [comment]
merged
