### ISSUE TITLE
esxi_guest sub directory

### ISSUE THREAD

**Issue by tamdavidson** [josenk/terraform-provider-esxi#209]
Unsure if I have missed it in the readme and other sources. However, I am struggling to see if it is possible to save/create/store esxi_guest VM in a subdirectory of a datastore.

Currently, when I run terra, the esxi_guest is saved in the root directory of the datastore, which is not the end of the world, but I want the esxi_guest to be stored in a sub-directory of the datastore. 

Is there a possibility to add a parameter such as "dir" or "sub-dir" that could be optionally supplied to allow the esxi_guest to be stored in a sub-directory?

**Comment by josenk** [comment]
ovftool creates the directories automatically, which matches the same naming convention as the ui.   It creates a dir based on the VM name....    I believe what you are referencing is when are manually moving things around in a ssh shell to the esxi host.   It's technically possible, but its better to keep standards.
