### ISSUE TITLE
SSH key auth for connect to esxi

### ISSUE THREAD

**Issue by UrusovVladimir** [josenk/terraform-provider-esxi#218]
How do i connect to esxi with ssh key? I don't want to use password because it's not safe enough.
Thanks!

**Comment by josenk** [comment]
The plugin uses ssh and ovftool.   Ovftool doesn't support ssh keys, so this plugin doesn't support ssh keys.

**Comment by iamjackg** [comment]
Looked into it some more. There is no mention of SSH in the ovftool manual. The only section talking about non-HTTP/HTTPS/FTP protocols has this to say:

![image](https://github.com/josenk/terraform-provider-esxi/assets/19474350/dc10ee8e-3f08-4cd3-ae77-f7bae95bdc77)

This seems to confirm that ovftool does not use SSH at all? The SSH package in the Go stdlib supports key authentication: https://pkg.go.dev/golang.org/x/crypto/ssh#PublicKeys
