### ISSUE TITLE
Attached shared disk to the new created VM

### ISSUE THREAD

**Issue by ynixon** [josenk/terraform-provider-esxi#22]
Hi,
can we attach an existing disk to the VM we are just creating ?

**Comment by josenk** [comment]
Sorry.  Currently, it doesn't support shared disks.  I want to add that feature in the future...

**Comment by josenk** [comment]
BTW:  I've added support to attach an existing (non-shared) disk to the VM...
>https://github.com/josenk/terraform-provider-esxi/releases/tag/V1.3.0
