### ISSUE TITLE
SSH Handshake Auth Failure

### ISSUE THREAD

**Issue by IonizeCbr** [josenk/terraform-provider-esxi#26]
`make` is failing with

`* provider.esxi: Failed to connect to esxi host: Client Connection Error`

my `variables.tf` file

```#
#  See https://www.terraform.io/intro/getting-started/variables.html for more details.
#

variable "esxi_hostname" { default = "example.com" }
variable "esxi_hostport" { default = "22" }
variable "esxi_username" { default = "root" }
variable "esxi_password" { default = "Password" }
```

The Error

```
 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none keyboard-interactive], no supported methods remain
[DEBUG] plugin.terraform-provider-esxi_v1.3.0: pid-41188-esxi_remote_cmds.go:38: [runRemoteSshCommand] Retry connection: 10
...9,8,7,6,etc.
```

sshd_config
```
PubkeyAuthentication no
ChallengeResponseAuthentication yes
PasswordAuthentication yes
```

Version Info
```
Terraform version: 0.11.10  
Free Esxi 6.0
go version go1.11 linux/amd64
```

When I write a manual ssh session in go it works fine. 
The interesting thing is when I run a `ssh -v` the authentication for the server reports

`Authentications that can continue: password,keyboard-interactive`

Then in the error message above it exclaims that only `[none keyboard-interactive]` are being used why are we not using simple password auth ?

Any Ideas what might be going wrong with the handshake as I've tried debugging and passively observing traffic to no avail ?

Thankyou

**Comment by josenk** [comment]
main.tf is the entry point for Terraform, not variables.tf...  I'll need to see the provider section of main.tf.  That is where you tell Terraform how to login to esxi.   variables.tf is just another file and you're just defining some variables in it.   We need to verify that you are using those variables in the main.tf.   main.tf should probably look something like this:
```
  provider "esxi" {
  esxi_hostname  = "${var.esxi_hostname}"
  esxi_hostport  = "${var.esxi_hostport}"
  esxi_username  = "${var.esxi_username}"
  esxi_password  = "${var.esxi_password}"
}
``` 

What OS is your PC/laptop/workstation that you're running this terraform command?

**Comment by IonizeCbr** [comment]
https://github.com/josenk/terraform-provider-esxi/blob/master/examples/02%20Cloned%20Guest%20-%20Complete%20build/variables.tf

I used this template as I'm cloning I do also have a main.tf it is as follows:
```
#########################################
#  ESXI Provider host/login details
#########################################
#
#   Use of variables here to hide/move the variables to a separate file
#
provider "esxi" {
  esxi_hostname  = "${var.esxi_hostname}"
  esxi_hostport  = "${var.esxi_hostport}"
  esxi_username  = "${var.esxi_username}"
  esxi_password  = "${var.esxi_password}"
}

resource "esxi_guest" "machine1" {
  guest_name = "${var.esxi_username}-1"
  disk_store = "iSCSI-1"
  guestos = "ubuntu-64"
  boot_disk_type = "thin"
  boot_disk_size = "20"
  memsize = "2048"
  numvcpus           = "1"
  resource_pool_name = "/"
  power              = "on"

  clone_from_vm = "TEMPLATE-VM"

  network_interfaces = [
    {
      virtual_network = "LAB"
    },
  ]

  guest_startup_timeout  = 45
  guest_shutdown_timeout = 30
}

resource "esxi_guest" "machine2" {
  guest_name = "${var.esxi_username}-2"
  disk_store = "iSCSI-1"
  guestos = "ubuntu-64"
  boot_disk_type = "thin"
  boot_disk_size = "20"
  memsize = "2048"
  numvcpus           = "1"
  resource_pool_name = "/"
  power              = "on"

  clone_from_vm = "TEMPLATE-VM"

  network_interfaces = [
    {
      virtual_network = "LAB"
    },
  ]

  guest_startup_timeout  = 45
  guest_shutdown_timeout = 30
}
```

variables.tf
```
#  See https://www.terraform.io/intro/getting-started/variables.html for more details.
#

variable "esxi_hostname" { default = "example.com" }
variable "esxi_hostport" { default = "22" }
variable "esxi_username" { default = "root" }
variable "esxi_password" { default = "Password" }
```

ERROR
```
 ssh: handshake failed: ssh: unable to authenticate, attempted methods [none keyboard-interactive], no supported methods remain

[DEBUG] plugin.terraform-provider-esxi_v1.3.0: pid-41188-esxi_remote_cmds.go:38: [runRemoteSshCommand] Retry connection: 10
```

**Comment by josenk** [comment]
Has it ever worked, can you try another workstation...   Can you try another esxi host.  There may be some sshd_config settings that are non-standard???

The plugin code is just doing a simple ssh login....   Can you provide your example "When I write a manual ssh session in go it works fine."

**Comment by josenk** [comment]
This problem might be related to special characters in the password...   Please verify using the latest release that has a fix.
>https://github.com/josenk/terraform-provider-esxi/releases/tag/1.4.0
