### ISSUE TITLE
Error terraform init  ()

### ISSUE THREAD

**Issue by emathias** [josenk/terraform-provider-esxi#27]
Hi, 

I already successfully used ESXi provider in the past. 

For some reason,  'terraform init' is now failing.   I would say esxi provider disappeared from here: 
https://releases.hashicorp.com/

Here's the log I'm getting:

$terraform init

2019/01/25 10:23:47 [INFO] Terraform version: 0.11.11
2019/01/25 10:23:47 [INFO] Go runtime version: go1.11.4
2019/01/25 10:23:47 [INFO] CLI args: []string{"/usr/local/Cellar/terraform/0.11.11/bin/terraform", "init"}
2019/01/25 10:23:47 [DEBUG] Attempting to open CLI config file: /Users/i066716/.terraformrc
2019/01/25 10:23:47 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2019/01/25 10:23:47 [INFO] CLI command args: []string{"init"}
2019/01/25 10:23:47 [DEBUG] command: loading backend config file: /Users/i066716/Projects/cthulhu/infra/terraform/esxi
2019/01/25 10:23:47 [INFO] command: empty terraform config, returning nil
2019/01/25 10:23:47 [DEBUG] command: no data state file found for backend config
2019/01/25 10:23:47 [DEBUG] New state was assigned lineage "9d7ea07e-cb7f-7181-11ec-35689a4a9146"
2019/01/25 10:23:47 [INFO] command: backend initialized: <nil>
2019/01/25 10:23:47 [DEBUG] checking for provider in "."
2019/01/25 10:23:47 [DEBUG] checking for provider in "/usr/local/Cellar/terraform/0.11.11/bin"
2019/01/25 10:23:47 [DEBUG] checking for provisioner in "."
2019/01/25 10:23:47 [DEBUG] checking for provisioner in "/usr/local/Cellar/terraform/0.11.11/bin"
2019/01/25 10:23:47 [INFO] Failed to read plugin lock file .terraform/plugins/darwin_amd64/lock.json: open .terraform/plugins/darwin_amd64/lock.json: no such file or directory
2019/01/25 10:23:47 [INFO] command: backend <nil> is not enhanced, wrapping in local
2019/01/25 10:23:47 [TRACE] Preserving existing state lineage "51f8e835-280e-6f38-507d-5b99799b7845"
2019/01/25 10:23:47 [TRACE] Preserving existing state lineage "51f8e835-280e-6f38-507d-5b99799b7845"
2019/01/25 10:23:47 [DEBUG] checking for provider in "."
2019/01/25 10:23:47 [DEBUG] checking for provider in "/usr/local/Cellar/terraform/0.11.11/bin"
2019/01/25 10:23:47 [DEBUG] plugin requirements: "esxi"=""

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
2019/01/25 10:23:47 [ERROR] failed to fetch plugin versions from https://releases.hashicorp.com/terraform-provider-esxi/
403 Forbidden
<html>
<head><title>403 Forbidden</title></head>
<body>
<h1>403 Forbidden</h1>
<ul>
<li>Code: AccessDenied</li>
<li>Message: Access Denied</li>
<li>RequestId: 6678949B94C4C134</li>
<li>HostId: kNKNddR1cdajGlxkG6gAqE0QLsFFrZCctipUa163f+KQSxu0zWh67Wp/HwzjAxKQe8PzG86+DBY=</li>
</ul>
<hr/>
</body>
</html>

2019/01/25 10:23:47 [ERROR] 1 error(s) occurred:

* no provider exists with the given name
2019/01/25 10:23:47 [DEBUG] plugin: waiting for all plugin processes to complete...
Provider "esxi" not available for installation.

A provider named "esxi" could not be found in the official repository.

This may result from mistyping the provider name, or the given provider may
be a third-party provider that cannot be installed automatically.

In the latter case, the plugin must be installed manually by locating and
downloading a suitable distribution package and placing the plugin's executable
file in the following directory:
    terraform.d/plugins/darwin_amd64

Terraform detects necessary plugins by inspecting the configuration and state.
To view the provider versions requested by each module, run
"terraform providers".

Thanks for your help!

**Comment by silasb** [comment]
The plugin should be in `$HOME/.terraform.d/plugins/terraform-provider-esxi_v1.4.0` as an example.
