### ISSUE TITLE
VM Not Getting created if I specify the ovf_source.

### ISSUE THREAD

**Issue by wallacepf** [josenk/terraform-provider-esxi#35]
Hello Fellows,

I'm getting the following error when specifying the ovf_source: 

PS C:\Users\walla\OneDrive\Dev\Terraform\kubernetes> terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + esxi_guest.vmtest01
      id:                                   <computed>
      boot_disk_size:                       <computed>
      boot_disk_type:                       "thin"
      disk_store:                           "datastore1"
      guest_name:                           "vmtest01"
      guest_shutdown_timeout:               "20"
      guest_startup_timeout:                "60"
      guestos:                              <computed>
      ip_address:                           <computed>
      memsize:                              <computed>
      network_interfaces.#:                 "1"
      network_interfaces.0.mac_address:     <computed>
      network_interfaces.0.nic_type:        <computed>
      network_interfaces.0.virtual_network: "MGMT"
      notes:                                <computed>
      numvcpus:                             <computed>
      ovf_source:                           "coreos_production_vmware_ova.ova"
      power:                                "on"
      resource_pool_name:                   <computed>
      virthwver:                            <computed>

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

esxi_guest.vmtest01: Creating...
  boot_disk_size:                       "" => "<computed>"
  boot_disk_type:                       "" => "thin"
  disk_store:                           "" => "datastore1"
  guest_name:                           "" => "vmtest01"
  guest_shutdown_timeout:               "" => "20"
  guest_startup_timeout:                "" => "60"
  guestos:                              "" => "<computed>"
  ip_address:                           "" => "<computed>"
  memsize:                              "" => "<computed>"
  network_interfaces.#:                 "" => "1"
  network_interfaces.0.mac_address:     "" => "<computed>"
  network_interfaces.0.nic_type:        "" => "<computed>"
  network_interfaces.0.virtual_network: "" => "MGMT"
  notes:                                "" => "<computed>"
  numvcpus:                             "" => "<computed>"
  ovf_source:                           "" => "coreos_production_vmware_ova.ova"
  power:                                "" => "on"
  resource_pool_name:                   "" => "<computed>"
  virthwver:                            "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* esxi_guest.vmtest01: 1 error(s) occurred:

* esxi_guest.vmtest01: There was an ovftool Error: Opening OVA source: coreos_production_vmware_ova.ova
The manifest validates
Opening VI target: vi://root@192.168.1.100:443/
Error: Invalid target name ("MGMT") specified in net mapping. OVF networks:   VM Network. Target networks:   DMZ  LAN  MGMT  Transit Network  VM Network  WAN  WIFI
Completed with errors

exit status 1

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Following the error message, I changed the network name back to "VM Network". Here's the results:

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

esxi_guest.vmtest01: Creating...
  boot_disk_size:                       "" => "<computed>"
  boot_disk_type:                       "" => "thin"
  disk_store:                           "" => "datastore1"
  guest_name:                           "" => "vmtest01"
  guest_shutdown_timeout:               "" => "20"
  guest_startup_timeout:                "" => "60"
  guestos:                              "" => "<computed>"
  ip_address:                           "" => "<computed>"
  memsize:                              "" => "<computed>"
  network_interfaces.#:                 "" => "1"
  network_interfaces.0.mac_address:     "" => "<computed>"
  network_interfaces.0.nic_type:        "" => "<computed>"
  network_interfaces.0.virtual_network: "" => "VM Network"
  notes:                                "" => "<computed>"
  numvcpus:                             "" => "<computed>"
  ovf_source:                           "" => "coreos_production_vmware_ova.ova"
  power:                                "" => "on"
  resource_pool_name:                   "" => "<computed>"
  virthwver:                            "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* esxi_guest.vmtest01: 1 error(s) occurred:

* esxi_guest.vmtest01: There was an ovftool Error: Error: Unexpected option: vi://root:<mypassword>@192.168.1.100/
Completed with errors

exit status 1

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Any help will be highly appreciated.

Thanks for this project

**Comment by josenk** [comment]
For some reason, ovftool doesn't find your network "MGMT", or "VM Network"???  Have you tried other ova/ovf/vmx sources?

   BTW:  "VM Network" is an example, do you actually have a virtual network called "VM Network"?

Verify that these names do not contain spaces before or after.

Enable Terraform debugging (export TF_LOG=DEBUG) and look for the ovftool command.  You'll see a line that looks something like this.
```
plugin.terraform-provider-esxi_v1.4.1: pid-9840-guest-create.go:217: [guestCREATE] ovf_cmd: ovftool --acceptAllEulas --noSSLVerify ....
```
  Try running the ovftool command manually.   If it doesn't work manually, it won't work within the plugin...

**Comment by wallacepf** [comment]
> For some reason, ovftool doesn't find your network "MGMT", or "VM Network"??? Have you tried other ova/ovf/vmx sources?
> 
> BTW: "VM Network" is an example, do you actually have a virtual network called "VM Network"?
> 
> Verify that these names do not contain spaces before or after.
> 
> Enable Terraform debugging (export TF_LOG=DEBUG) and look for the ovftool command. You'll see a line that looks something like this.
> 
> ```
> plugin.terraform-provider-esxi_v1.4.1: pid-9840-guest-create.go:217: [guestCREATE] ovf_cmd: ovftool --acceptAllEulas --noSSLVerify ....
> ```
> Try running the ovftool command manually. If it doesn't work manually, it won't work within the plugin...

I don't have it, but i just tested with it. Here's the output with the debug:

I ran the ovftool straight from my PS


```
PS C:\Users\walla\OneDrive\Dev\Terraform\kubernetes> ovftool --acceptAllEulas --noSSLVerify --X:useMacNaming=false -dm=thin --name=nostradamus-01 --overwrite -ds=datastore1  --network="MGMT" coreos_production_vmware_ova.ova vi://root:<mypass>@192.168.1.100/
Opening OVA source: coreos_production_vmware_ova.ova
The manifest validates
Opening VI target: vi://root@192.168.1.100:443/
Warning:
 - Line 129: Unable to parse 'enableMPTSupport' for attribute 'key' on element 'Config'.
Deploying to VI: vi://root@192.168.1.100:443/
Transfer Completed
Completed successfully
PS C:\Users\walla\OneDrive\Dev\Terraform\kubernetes>
```


And here is the VM:

![image](https://user-images.githubusercontent.com/4224243/52916392-95815680-32bd-11e9-9a41-ce355c3b489f.png)

Now, trying straight from the Terraform (changing the name to Nostradamus-02):

```
2019/02/17 14:10:30 [TRACE] root: eval: *terraform.EvalWriteState
2019/02/17 14:10:30 [TRACE] root: eval: *terraform.EvalApplyProvisioners
2019/02/17 14:10:30 [TRACE] root: eval: *terraform.EvalIf
2019/02/17 14:10:30 [TRACE] root: eval: *terraform.EvalWriteState
2019/02/17 14:10:30 [TRACE] root: eval: *terraform.EvalWriteDiff
2019/02/17 14:10:30 [TRACE] root: eval: *terraform.EvalApplyPost
2019/02/17 14:10:30 [ERROR] root: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

* esxi_guest.nostradamus-02: There was an ovftool Error: Opening OVA source: coreos_production_vmware_ova.ova
The manifest validates
Opening VI target: vi://root@192.168.1.100:443/
Error: Invalid target name ("MGMT") specified in net mapping. OVF networks:   VM Network. Target networks:   DMZ  LAN  MGMT  Transit Network  VM Network  WAN  WIFI
Completed with errors

exit status 1
2019/02/17 14:10:30 [ERROR] root: eval: *terraform.EvalSequence, err: 1 error(s) occurred:

* esxi_guest.nostradamus-02: There was an ovftool Error: Opening OVA source: coreos_production_vmware_ova.ova
The manifest validates
Opening VI target: vi://root@192.168.1.100:443/
Error: Invalid target name ("MGMT") specified in net mapping. OVF networks:   VM Network. Target networks:   DMZ  LAN  MGMT  Transit Network  VM Ne2019/02/17 14:10:30 [DEBUG] plugin: waiting for all plugin processes to complete...
2019-02-17T14:10:30.103-0300 [DEBUG] plugin.terraform-provider-esxi_v1.4.1.exe: pid-18476-rpc_server.go:48: [ERR] plugin: plugin server: accept tcp 127.0.0.1:10000: use of closed network connection

Error: Error applying plan:

1 error(s) occurred:

* esxi_guest.nostradamus-02: 1 error(s) occurred:

* esxi_guest.nostradamus-02: There was an ovftool Error: Opening OVA source: coreos_production_vmware_ova.ova
The manifest validates
2019-02-17T14:10:30.122-0300 [DEBUG] plugin: plugin process exited: path=C:\Users\walla\AppData\Roaming\terraform.d\plugins\terraform-provider-esxi_v1.4.1.exe
Opening VI target: vi://root@192.168.1.100:443/
Error: Invalid target name ("MGMT") specified in net mapping. OVF networks:   VM Network. Target networks:   DMZ  LAN  MGMT  Transit Network  VM Network  WAN  WIFI
Completed with errors

exit status 1


Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


PS C:\Users\walla\OneDrive\Dev\Terraform\kubernetes>
```

Here are the [guestCREATE] lines:

```
2019-02-17T14:10:29.849-0300 [DEBUG] plugin.terraform-provider-esxi_v1.4.1.exe: pid-18476-guest_functions.go:25: [guestGetVMID] result:
2019-02-17T14:10:29.850-0300 [DEBUG] plugin.terraform-provider-esxi_v1.4.1.exe: pid-18476-guest-create.go:217: [guestCREATE] ovf_cmd: ovftool --acceptAllEulas --noSSLVerify --X:useMacNaming=false -dm=thin --name=nostradamus-02 --overwrite -ds=datastore1  --network="MGMT" coreos_production_vmware_ova.ova vi://root:<mypass>@192.168.1.100/
2019-02-17T14:10:30.096-0300 [DEBUG] plugin.terraform-provider-esxi_v1.4.1.exe: pid-18476-guest-create.go:221: [guestCREATE] ovftool output: "Opening OVA source: coreos_production_vmware_ova.ova\r\nThe manifest validates\r\nOpening VI target: vi://root@192.168.1.100:443/\r\nError: Invalid target name (\"MGMT\") specified in net mapping. OVF networks:   VM Network. Target networks:   DMZ  LAN  MGMT  Transit Network  VM Network  WAN  WIFI\r\nCompleted with errors\r\n"
```

**Comment by josenk** [comment]
It looks like your manual command and the command from the plugin are the same.   It's very strange that you get an error message from ovftool within the plugin???


1) Is coreos_production_vmware_ova.ova modified or is it the original download from coreos.com website?  I ask because I googled some issues with your error message that implies there could be more than 1 network interface configured in the ova file.

2) Have you built anything successful using the plug thus far?

**Comment by wallacepf** [comment]
> It looks like your manual command and the command from the plugin are the same. It's very strange that you get an error message from ovftool within the plugin???
> 
> 1. Is coreos_production_vmware_ova.ova modified or is it the original download from coreos.com website?  I ask because I googled some issues with your error message that implies there could be more than 1 network interface configured in the ova file.
> 2. Have you built anything successful using the plug thus far?

1 - Yes, this is the original ova downloaded from coreos website (Using Invoke-WebRequest command in PS)
2 - I ran the VM test example and it worked.

**Comment by josenk** [comment]
Did you use "MGMT" for the examples also?

Can you try using Terraform on a MAC or Linux system?   I'm wondering if there's any issue with Windows?   I tried a Windows system using the same coreos and it worked...

If you still have problems, please post your main.tf and variables.tf (remove your password if it's there...)

**Comment by wallacepf** [comment]
Solved with Linux!

**Comment by daximus522** [comment]
When executing similar commands on Windows I was getting similar errors until I selected a network name with a space in it.  When the plugin generates the OVFTool command the flag generated looks like:

--net="DMZ" 

However after testing the command manually it needs to be:

--net=DMZ

The only way I was able to overcome this on Windows was choose a network name with a space in it.
is generated parameter
