### ISSUE TITLE
Building The Provider 1.4.1 - MACOS 10.14.3

### ISSUE THREAD

**Issue by eltphat** [josenk/terraform-provider-esxi#38]
This is just a guide. How to build the provider for MacOS.
Many Thanks author and contributors.
----------------------
sudo export GOPATH="/usr/local"

sudo mkdir -p $GOPATH/src/golang.org/x/
cd $GOPATH/src/golang.org/x/
sudo git clone https://github.com/golang/crypto.git

sudo mkdir -p $GOPATH/src/github.com/hashicorp
cd $GOPATH/src/github.com/hashicorp
sudo git clone https://github.com/hashicorp/terraform.git

mkdir -p $GOPATH/src/github.com/josenk
cd $GOPATH/src/github.com/josenk
git clone https://github.com/josenk/terraform-provider-esxi.git

cd $GOPATH/src/github.com/josenk/terraform-provider-esxi
sudo go build -o terraform-provider-esxi_`cat version`

sudo cp terraform-provider-esxi_`cat version` ~/.terraform.d/plugins/

**Comment by josenk** [comment]
Thanks for the suggestion.   I see this doesn't really work.    We are in the middle of re-visiting the build section of README.    I'll make sure it's assumed your doing work as non-root in the next release.

If you set your GOPATH to something in your home dir, you can run all the commands without sudo.   If required, sudo will be needed if you want to copy the plugin to a system-wide path (like /usr/local/bin).

**Comment by eltphat** [comment]
I ran above command and it worked.

**Comment by josenk** [comment]
Fixed docs in 1.4.2.
