### ISSUE TITLE
interface limits...

### ISSUE THREAD

**Issue by hidethecode** [josenk/terraform-provider-esxi#39]
Why I can create not more than 3 network interfaces? Could you provide the ability to create a dynamic count of interfaces?

thanks

**Comment by josenk** [comment]
It's on my todo list to allow the maximum limit of 10...

>https://configmax.vmware.com

**Comment by hidethecode** [comment]
thanks. I will wait

**Comment by josenk** [comment]
Should be fixed in 1.4.2
