### ISSUE TITLE
main.go:6:2: local import "./esxi" in non-local package

### ISSUE THREAD

**Issue by mft3000** [josenk/terraform-provider-esxi#4]
Hi Jonatan,

maybe you forgot to change import paths on main.go (you leaved ./esxi) 👍 

sed -i 's/.\/esxi/github.com\/terraform-providers\/terraform-provider-esxi\/esxi/g' main.go
to fix it

I want to be paid for bug hunting ahahha... just joking :) thank you for your great job 

Francesco

https://github.com/josenk/terraform-provider-esxi/blob/77668e6a59e9f4198b51e1315bbd5002b2a0718d/main.go#L6

**Comment by josenk** [comment]
Lol.   fixed in 1.02a
>https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.0.2a

Sorry, I skipped a step in my validation and this problem passed through...
