### ISSUE TITLE
No destroy when add new network adapter

### ISSUE THREAD

**Issue by JSFonta** [josenk/terraform-provider-esxi#42]
Hello,

We use your tool to deploy some VM with a PFSense's OVF on ESXi Free. We have to add more adapter to our VM, but when we try to do that, it wants to destroy and create the VM rather than just modify it.

Is it possible to add this feature please ?

Thanks,

Doug.

**Comment by josenk** [comment]
Should be fixed in v1.5.0
>https://github.com/josenk/terraform-provider-esxi/releases/tag/1.5.0
