### ISSUE TITLE
Set credentials for ova

### ISSUE THREAD

**Issue by bylek** [josenk/terraform-provider-esxi#43]
Hi, I'm using Ubuntu 18.04 ova image (https://cloud-images.ubuntu.com/releases/18.04/release/ubuntu-18.04-server-cloudimg-amd64.ova). Is it possible to set password or ssh key for default user?

**Comment by silasb** [comment]
I haven't tried using cloud-init with Ubuntu (only CoreOS), but I'd start by looking there.

**Comment by josenk** [comment]
There's choices...   Yes, Cloud-init should work out of the box. 

You may want to look into all the provisioners.
>https://www.terraform.io/docs/provisioners/index.html

**Comment by bylek** [comment]
Thanks guys, this is a good lead.
