### ISSUE TITLE
connectToHost should allow ssh authentication via public key / private key

### ISSUE THREAD

**Issue by rodrigc** [josenk/terraform-provider-esxi#44]
The `connectToHost` function:

https://github.com/josenk/terraform-provider-esxi/blob/9ae5270742de1476f2ef44cb77cbcd479c22f711/esxi/esxi_remote_cmds.go#L12 

should be extended to allow password-less auth, if I copy my SSH public key to the authorized_keys file on the ESXi server.

**Comment by josenk** [comment]
Great suggestion, but ovftool doesn't support using passwordless ssh keys. So you'll be prompted for a password anyway.

**Comment by tbennett6421** [comment]
@josenk  Hypothetical question. If this was setup to allow public key authentication to the ESXi server would it be possible to prompt the user, and handle passing the credentials to ovftool?

We are using this solution for rapid deployment of security testing labs and this would be nice to have an option to avoid embedding credential either in variables or within the main tf file itself. The idea being that the terraform config and connection can be secured over public key auth and prompt the user deploying the infrastructure to enter credentials for OVFtool, kinda like when terraform asks you to confirm modifcation/destructive actions

My golang is really rusty, so I wanted to run it by you first to see if it would be feasible

**Comment by josenk** [comment]
Terraform supports so many forms of reading variables.   files, environment variables, prompt, consul, vault, etc...  I don't think it's worth anyone's time to add support for ssh keys in the plugin when ovftool doesn't.
