### ISSUE TITLE
Configuring Networking - vSwitches and Port Groups etc.

### ISSUE THREAD

**Issue by berney** [josenk/terraform-provider-esxi#47]
Do you plan to add the ability to configure ESXi networking like vSwitches and Port Groups etc?

Right now I use Ansible to configure some things, but not everything. Ideally, I'd prefer to do it all in Terraform and not have to use Ansible.

If you are interested, if I can find the time I could add some functionality using the SSH `esxcli` commands. Since `ssh` is already being used.

**Comment by josenk** [comment]
I wasn't really thinking of adding those resources...   If there's a big demand, I may consider it.

**Comment by tbennett6421** [comment]
+1 I think that's a good option. We use terraform for labbing and this would be handy to setup instances of labs separate from other people's labs by vlan. Can be done manually but I like the ideas

**Comment by wallacepf** [comment]
+1

**Comment by jability** [comment]
This is exactly what I was looking to accomplish. That would be a terrific feature to have.

**Comment by dzflack** [comment]
@josenk I've started adding support for these resource (i.e. vswitches/portgroups); would you be open to pulling in these changes if I submit a PR?

**Comment by josenk** [comment]
@dzflack , for sure...   I haven't really had much time to work on this feature and I also don't really have any infra to test.   If you are willing to help support this new feature, it would be great to add it.   There does seem to be some demand.

**Comment by dzflack** [comment]
Initial PR is up [here](https://github.com/josenk/terraform-provider-esxi/pull/105).

@josenk please can you have a quick look through and give some feedback around any areas of concern.

**Comment by josenk** [comment]
vswitch and portgroup support has been added.
> https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.8.0
