### ISSUE TITLE
There was an ovftool Error: exit status 127

### ISSUE THREAD

**Issue by kjpkjp28** [josenk/terraform-provider-esxi#50]
Hi 
wondering if anybody run into below error.
---
esxi_guest.vmtest: Creating...
  boot_disk_size:                       "" => "<computed>"
  clone_from_vm:                        "" => "testbox01"
  disk_store:                           "" => "datastore01"
  guest_name:                           "" => "vmtest"
  guest_shutdown_timeout:               "" => "<computed>"
  guest_startup_timeout:                "" => "<computed>"
  guestos:                              "" => "<computed>"
  ip_address:                           "" => "<computed>"
  memsize:                              "" => "<computed>"
  network_interfaces.#:                 "" => "1"
  network_interfaces.0.mac_address:     "" => "<computed>"
  network_interfaces.0.nic_type:        "" => "<computed>"
  network_interfaces.0.virtual_network: "" => "LAN Network"
  notes:                                "" => "<computed>"
  numvcpus:                             "" => "<computed>"
  power:                                "" => "on"
  resource_pool_name:                   "" => "<computed>"
  virthwver:                            "" => "<computed>"
  virtual_disks.#:                      "" => "<computed>"

Error: Error applying plan:

1 error occurred:
        * esxi_guest.vmtest: 1 error occurred:
        * esxi_guest.vmtest: There was an ovftool Error:
exit status 127

**Comment by kjpkjp28** [comment]
haha i needed to install vmwre ovftool package, worked like a charm.
excellent work on your part. Thanks

**Comment by josenk** [comment]
Ahh, Great to know...   I guess that makes sense.
>https://stackoverflow.com/questions/1763156/127-return-code-from
