### ISSUE TITLE
The virtual machine receives the same DHCP IP address as the previous one, even if it has a different MAC address.

### ISSUE THREAD

**Issue by SergeFocus** [josenk/terraform-provider-esxi#54]
Hey all,

I'm having an issue on the latest Ubuntu image (ubuntu-18.04- 201806.08.0) where every VMachine I start gets assigned the same DHCP IP address as the previous. even terraform destroying it and recreating it gets the same IP (even though it has a different MAC address).
The hostnames and MAC addresses are different between the two machines. dhclient correctly claims two separate IPs, but the resolver in use is systemd-networkd.
systemd-networkd uses a different method to generate the DUID than dhclient. dhclient by default uses the link-layer address while systemd-networkd uses the contents of /etc/machine-id. Since the VMs were cloned, they have the same machine-id and the DHCP server returns the same IP for both.

To fix, replace the contents of one or both of /etc/machine-id. This can be anything, but deleting the file and running systemd-machine-id-setup will create a random machine-id in the same way done on machine setup. 
For example `rm -rf /etc/machine-id && systemd-machine-id-setup`

**Comment by josenk** [comment]
Nothing what you describe here makes me feel that this is a problem with the plugin...

If you are having problems with a particular image, you might want to fix it or try a new image. For example, can you delete that file in the source.

**Comment by SergeFocus** [comment]
Thank. That's exactly what I did. The question is closed.
