### ISSUE TITLE
Build instructions fail #2

### ISSUE THREAD

**Issue by DimDroll** [josenk/terraform-provider-esxi#55]
Hello Jonathan,

Thank you for an awesome plugin, great work!

Seems like local import sneak into the code once more:
https://github.com/josenk/terraform-provider-esxi/commit/b2cd626d3c7697f7715496125d1563ea3435ba20

It's in released version and in master currently.

Created small PR: https://github.com/josenk/terraform-provider-esxi/pull/56

Previous case:
https://github.com/josenk/terraform-provider-esxi/issues/32

**Comment by rpeets** [comment]
I have the same issue.
```
:➜  go get -u -v github.com/josenk/terraform-provider-esxi
github.com/josenk/terraform-provider-esxi (download)
github.com/hashicorp/terraform (download)
package terraform-provider-esxi/esxi: unrecognized import path "terraform-provider-esxi/esxi" (import path does not begin with hostname)
```
