### ISSUE TITLE
Unable to create multiple network adapters

### ISSUE THREAD

**Issue by nsdc92** [josenk/terraform-provider-esxi#58]
Terraform 0.12.5
terraform-provider-esxi_v1.5.0.exe
Windows 10 Pro 1903

I am unable to create multiple nics using the syntax described here: https://github.com/josenk/terraform-provider-esxi#how-to-use-and-configure-a-maintf-file

When I run _terraform validate_ I receive this error:
```
Error: Unsupported argument

  on main.tf line 17, in resource "esxi_guest" "WINDOWS10":
  17:   network_interfaces = [

An argument named "network_interfaces" is not expected here. Did you mean to
define a block of type "network_interfaces"?
```

Here is a copy of my [main.tf.txt](https://github.com/josenk/terraform-provider-esxi/files/3437486/main.tf.txt)

Network adapter creation works fine when I only need one network adapter created and use this syntax:
```
  network_interfaces {
    virtual_network = "HOME" 
  }
```

**Comment by josenk** [comment]
you are using the old 0.11 ferraform format.   Convert your tf files to 0.12 format.
https://www.terraform.io/upgrade-guides/0-12.html

**Comment by nsdc92** [comment]
I had issues running terraform 0.12upgrade, due to already having a version.tf file claiming 0.12 was supported. I deleted the file and re-ran the command. That fixed it. Thank you much.

**Comment by HelioGuilherme66** [comment]
@nsdc92 Hello. I have the same problem, but I can't find a solution. Can you show how the block is after fixing?

I have:
```
network_interfaces {
    virtual_network = var.virtual_network
}
```
I need to add another NIC:
```
virtual_network = "NAT"
```
---
Found an example https://github.com/josenk/terraform-provider-esxi/issues/103#issue-574580558

Just duplicate the block.
