### ISSUE TITLE
can some one explain in details of using clone_from_vm and ovf_source

### ISSUE THREAD

**Issue by gudipudipradeep** [josenk/terraform-provider-esxi#59]
I am trying to deploy server using terraform.. Before that where I need to **install ovftool inside the esxi server or terraform server..?** 

**clone_from_vm** argument will take running server name is it..? if it is I am facing following 
I install the ovftool inside the terraform server
clone_from_vm="CentosServer-Node04"

**issue.
Error: There was an ovftool Error: Opening VI source: vi://username@host_name:443/CentosServer-Node04
Error: Fault cause: vim.fault.TaskInProgress**

I tried other way by using **guestos** option.
guestos="centos"
event I got the issue.
![Capture](https://user-images.githubusercontent.com/8638634/62159002-5e17db00-b32e-11e9-955b-72a703999b71.PNG)

I am usign this terraform-provider-esxi_v1.4.3.exe version.

Please guide me.

**Comment by josenk** [comment]
You install ovftool on your pc/laptop.  not the esxi server.  There is a Windows, Mac and Linux versions of ovftool.  I don't know what you mean by "Terraform Server"???

The clone_from_vm option requires that the source VM is powered OFF.

The ovf_source option is a file on your local PC/Laptop.    You can create this image yourself or you can download from the Internet.  Search Google to help you with either of these choices.

If you do not specify neither clone_from_vm, and ovf_source, then the VM will be build, but there is NO OS.  (As you see in your screenshot).   You need a PXE server to build your VMs if you want to use this option.

**Comment by gudipudipradeep** [comment]
Thanks for quick reply.

Due some of the issue with terraform-provider-esxi_v1.4.3.exe I am using terraform-provider-esxi_v1.5.0.exe. when I deploy my terraform with terraform apply command 
It is continuesly running with any issue but VMWare no VM are Created I waited for 5hours.

So that I started debugging actually **When we run terraform apply command it created one ovf_cmd.bat inside the folder** I was copyed it run through command line I got following issue.
**ovftool --acceptAllEulas --noSSLVerify --X:useMacNaming=false -dm=thin --name="K8SMasterPradeep" --overwrite -ds="datastore1"  "vi://username:paswwrod@hostname/Linux" "vi://username:password@hostname/"

Transfer Failed
Error: Failed to open file stream: https://host_name:443/ha-nfc/xxxx-xxxx-xxxx-c1cb-a55a4fdb76f3/disk-0.vmdk
Completed with errors**

but after some time **I was kill the process of running terraform apply i think it is showing that it is asking password but it is not visible at the time of running terraform apply command.**

**Error: There was an ovftool Error:
C:\Users\username\Documents\Documents>ovftool --acceptAllEulas --noSSLVerify --X:useMacNaming=false -dm=thin --name="K8SMasterPradeep" --overwrite -ds="datastore1"  "vi://username:password@hostname/Linux" "vi://username:password@hostname/"
Enter login information for source vi://source_hostname/
Username: username
Password: *********
Enter login information for source vi://target_hostname/
Username: username
Password:
Error: Login aborted
Completed with errors**

My Terraform Code:
**
resource "esxi_guest" "K8SMasterPradeep" {
    guest_name="K8SMasterPradeep"
	clone_from_vm="Linux"
	memsize="8192"
	numvcpus="2"
	disk_store = "datastore1" 
    network_interfaces {
         virtual_network = "VM Network"
    }
}
**
