### ISSUE TITLE
ip_address is not getting while in provisioner

### ISSUE THREAD

**Issue by gudipudipradeep** [josenk/terraform-provider-esxi#60]
`resource "esxi_guest" "K8SMaster" {
  guest_name="K8SMaster-${var.product}"
	clone_from_vm="${var.linux_image}"
	memsize="8192"
	numvcpus="2"
	disk_store = "${var.disk_store}"   # Required, Specify an existing Disk Store

  provisioner "remote-exec" {
    inline = [
      "ls -a",
      "hostname",
      ""
    ]
    connection {
      host="${self.ip_address}"
      type="ssh"
      user="xxx"
      password="xxxx"
    }
  }
  **provisioner "local-exec" {
    command = " echo ${esxi_guest.K8SMaster.ip_address}" >> private_ips.txt"
  }**
	virtual_disks {
      virtual_disk_id = esxi_virtual_disk.K8SMasterDisk.id
      slot = "0:1"
    }
	
    network_interfaces {
         virtual_network = "VM Network" # Required for each network interface, Specify the Virtual Network name.
    }
}	`

Ip address is not pushing to the  private_ips.txt file and some time ip_address is not able to print in output.

**Comment by josenk** [comment]
Do you have open-vm-tools installed on the source?  It's a requirement.

**Comment by gudipudipradeep** [comment]
yes it is..

**Comment by josenk** [comment]
You may need to increase guest_startup_timeout.

There is two methods to try to get the ip...   You can enable terraform debugging, or look at the code.

**Comment by gudipudipradeep** [comment]
by updating guest_startup_timeout it is working but is there any why to check the status of the vm like running or inprogress like this then it will be good i think so.

**Comment by josenk** [comment]
Not sure what status you're looking for?   It either has an ip or not.   As soon as an ip is found, its used.
