### ISSUE TITLE
Malfunction while guestinfo data are too large

### ISSUE THREAD

**Issue by Ankhterus** [josenk/terraform-provider-esxi#62]
Hi,

I try to mount a CoreOS cluster and VMWare Guestinfo provisioning fails when Ignition file gets too big (the VM boot without updated Guestinfo).

I don't know if it's a VMWare bug or something else. See attached [error.log](https://github.com/josenk/terraform-provider-esxi/files/3486982/error.log) extract.

Thanks!

**Comment by josenk** [comment]
Just to clarify, if you have a smaller Guestinfo it works???

**Comment by Ankhterus** [comment]
Yes, it works. It's drive me crazy. I think the command echoing the modified .vmx file fails due to some ESXi shell limits.

**Comment by josenk** [comment]
If there is a restriction of Guestinfo size, there's not much I can do about that.  You'll have to find a way to make it smaller or find another solution.   Try removing all unnecessary spaces and remarks...

**Comment by Ankhterus** [comment]
Hi,

I checked for a Guestinfo size and there is not: I succeeded to set Guestinfo using the ESXi Web console.

So I forked your code and did a very ugly fix by using SCP instead of echoing vmx file through ssh redirection and it's works!!!

I never did go language before so it's bad code. Can you check master branch of https://github.com/Ankhterus/terraform-provider-esxi or do you want me to do a PR?

Thanks for your project and your time by the way!

**Comment by silasb** [comment]
I also ended up running into this.

@Ankhterus I'll try your fork.  If everything works it might be time to move to sftp for transferring the VMX.

**Comment by josenk** [comment]
Sorry it took so long to implement...  But it's officially there now!

>https://github.com/josenk/terraform-provider-esxi/tree/v1.5.2
