### ISSUE TITLE
still creating ...VM not getting created

### ISSUE THREAD

**Issue by vidhyAdeza** [josenk/terraform-provider-esxi#63]
I am using .12 version. there is no error in plan but when I apply it keep on showing message "still creating...10s" like that

when I ctrl+c .. i see following 

```
Error: There was an ovftool Error:
C:\Users\Administrator\Documents\Learn\Terraforma_Ansible_Automation\terraform>ovftool --acceptAllEulas --noSSLVerify --X:useMacNaming=false -dm=thin --name="Kali2019.2-XFCE" --overwrite -ds="datastore1"  "C:\Users\Administrator\Documents\Virtual Machines\Kali2019.2-XFCE\Kali2019.2-XFCE.vmx" "vi://root:--------@esxi.mac.com/"
Opening VMX source: C:\Users\Administrator\Documents\Virtual Machines\Kali2019.2-XFCE\Kali2019.2-XFCE.vmx
Enter login information for target vi://esxi.mac.com/
Username: root
Password: **
Error: Login aborted
Completed with errors

exit status 1


  on main.tf line 8, in resource "esxi_guest" "ESXi-kali":
   8: resource "esxi_guest" "ESXi-kali" {
```

but if i copy paste the ovf command and run from cmd.. it  works !

here is my main.tf

```
`provider "esxi"{
  esxi_hostname = var.esxi_hostname
  esxi_hostport = var.esxi_hostport
  esxi_username = var.esxi_username
  esxi_password = var.esxi_password
}

resource "esxi_guest" "ESXi-kali" {
  guest_name        = "Kali2019.2-XFCE"
  disk_store        = "datastore1"
  power				= "on"
  ovf_source        = "C:\\Users\\Administrator\\Documents\\Virtual Machines\\Kali2019.2-XFCE\\Kali2019.2-XFCE.vmx"
  network_interfaces {
    
      virtual_network = "esxinet"
    
  }
  guest_startup_timeout = 45
  guest_shutdown_timeout = 30
}`
```

**Comment by vidhyAdeza** [comment]
This happens in Windows only ...tried on Ubuntu worked fine...

**Comment by josenk** [comment]
You might have a username/password issue.   To get some additional information about the problem, you need to debug a bit more....   Try logging into your esxi host and run this command while attempting to run `terraform apply`.

```
tail -f /var/log/auth.log
```

>https://www.ivobeerens.nl/2015/10/07/vmware-esxi6-password-policy/
>https://www.ivobeerens.nl/2018/01/02/esxi-root-account-locked/

**Comment by vidhyAdeza** [comment]
Okay. Thanks. 
But I used the same userame and password on Linux it worked. So its not username/pass problem. 
I will debug and dig more.

Anyway thanks so much for creating this provider ..it really helped me and saved a lot of money. :)

keep it up

Also I was interested in User data attributes but there is no documentation around it ..how to use those with the provider.

**Comment by josenk** [comment]
Sure, update the thread with your findings... 

Userdata examples can be found in the "examples" directory.   Look at example 4 & 5.

**Comment by stefaanc** [comment]
does your password contain special characters?

ovftool needs these to be in "%ASCII-hex" format - like "%40" for "@" (remark that 40 is a hex number), or "%5c" for "\"
however if you do specify your password like this, then you cannot connect to the esxi host

the only way I found around this (other than modifying the provider code) is to not use special chars in the password

**Comment by vidhyAdeza** [comment]
Yes, my password contained special chars.
But same ovftool work on Linux so I am wondering if it is just windows binary issue?

**Comment by stefaanc** [comment]
in my case it was '#'

**Comment by josenk** [comment]
I cannot make ovftool for windows work with the '#' character...   I tried on command line, in a batch and prompted.   I tried entering the '#' character and also tried the encoded '%23' string.

Are you able to use ovftool manually using the '#' character?

**Comment by dlee35** [comment]
It's basically taking every use of a special character and converting it to the numeric form of that key (! => 1, # => 3, etc). Examples:
r00t123# => r00t1233
ZAQ!xsw2 => ZAQ1xsw2

**Comment by dlee35** [comment]
However, I can deploy manually by running:
ovftool --acceptAllEulas --noSSLVerify --X:useMacNaming=false -dm=thin --name="vmtest" --overwrite -ds="datastore1"  "vi://testuser:ZAQ!xsw2@<IP_ADDRESS>/test-image-base" "vi://testuser:ZAQ!xsw2@<IP_ADDRESS>/"

**Comment by dlee35** [comment]
For what it's worth, I was able to overcome the issue by setting the `password` variable equal to the value stored in `c.esxiPassword` and recompiling the binary (or I guess s/password/c.esxiPassword in `dst_path` is another option).
//password := url.QueryEscape(c.esxiPassword)
password := c.esxiPassword

This is using Terraform v0.12.10-dev and VMware ovftool 4.3.0 (build-7948156).

Hope it helps!

**Comment by josenk** [comment]
The issue is not the "!" character.   It's the "#" character.  

   Your solution...   `password := c.esxiPassword` doesn't work with the '#' character.  Or any special character...  That's why QueryEscape is there!

ovftool doesn't seem to work for me if the password on my esxi server contains a '#' character.   I was asking if you get the same results...

**Comment by dlee35** [comment]
I'm sorry, but I disagree. This is not a `"Error: Could not lookup host:"` error with using "#". Yes, that issue exists as well. This error is in the use of special characters in general given the versions I stated above. If you would like for me to create a new issue, that is fine, but stating it's not a problem with X b/c Y is the only thing I know about isn't necessarily true. 

Case in point:

**Comment by josenk** [comment]
I found the root cause of the issue...  QueryEscape uses the '%' as the escape character, but windows also uses that character.   Basically, I needed to escape the escape character.

It's talked about in many places online, for example: https://www.robvanderwoude.com/escapechars.php

Special characters should now be working: https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.5.2

**Comment by vidhyAdeza** [comment]
Thanks. After v1.5.2 it works on windows. :)
