### ISSUE TITLE
ESXi Password required, but not prompting user for password

### ISSUE THREAD

**Issue by tbennett6421** [josenk/terraform-provider-esxi#64]
Running `terraform plan -input=true` doesn't appear to prompt the user for credentials. Instead the command fails with 
```
Error: Failed to connect to esxi host: Client Connection Error

  on main.tf line 1, in provider "esxi":
   1: provider "esxi" {
```

Is this expected behavior? I would think if ENV is not set, and the password is not provided then the application would prompt the user for a password.

From README.md
`esxi_password - Required`
https://learn.hashicorp.com/terraform/getting-started/variables.html#ui-input

---

I'm using the following config, Works fine when `esxi_password` is set and fails when esxi_password is not set.
```
provider "esxi" {
  esxi_hostname      = "${var.esxi_host}"
  esxi_hostport      = "${var.esxi_port}"
  esxi_username      = "${var.ssh_username}"
}
resource "esxi_guest" "lab_dc1" {
  guest_name = "lab.dc1"
  disk_store = "datastore1"
  network_interfaces {
    virtual_network = "VM Network"
  }
}
```

**Comment by tbennett6421** [comment]
A side effect is the entire ESXi hypervisor becomes unresponsive after one run and must be rebooted from our end.

**Comment by josenk** [comment]
You didn't do it correctly... esxi_password is a required param for the provider and you are missing it in your main.tf.  Setting it through an unset variable will prompt.  (-input=true is the default, so you don't need to specify it)

In your main.tf
```
provider "esxi" {
  esxi_hostname  = "${var.esxi_hostname}"
  esxi_hostport  = "${var.esxi_hostport}"
  esxi_username  = "${var.esxi_username}"
  esxi_password  = "${var.esxi_password}"
}
```
In your variables.tf, DON'T set a default for the pasword.
```
variable "esxi_hostname" { default = "esxi_IP" }
variable "esxi_hostport" { default = "22" }
variable "esxi_username" { default = "root" }
variable "esxi_password" { }
```

Getting locked out of your ESXi because you entered too many incorrect logins is by design and has nothing to do with this plugin.

  See section ESXi Account Lockout Behavior
>https://docs.vmware.com/en/VMware-vSphere/6.5/com.vmware.vsphere.security.doc/GUID-DC96FFDB-F5F2-43EC-8C73-05ACDAE6BE43.html

If you waited 15 minutes, logins would have been allowed again.

**Comment by tbennett6421** [comment]
Thank you for providing that piece of information. Reading the documentation wasn't clear that the variable had to be defined and blank. That being said, why does the plugin attempt to authenticate when there is no valid password defined or set? 

Additionally I only ran `terraform apply` once and yet it looks like it submitted 30+ login attempts to try and instantiate one vm. I would expect the process to fail after one authentication attempt.
