### ISSUE TITLE
ip_address attribute for esxi_guest resource is not available for the first run?

### ISSUE THREAD

**Issue by hieunba** [josenk/terraform-provider-esxi#66]
I was trying to use remote-exec provisioner but ip_address attribute was not available while applying the Terraform plan.
It did exist when issuing `terraform refresh` after applying the plan.

**Comment by josenk** [comment]
Try this setting:  
  - guest_startup_timeout - Optional - The amount of guest uptime, in seconds, to wait for an available IP address on this virtual machine.

**Comment by hieunba** [comment]
@josenk It works perfectly
