### ISSUE TITLE
ovf_source fails with ovftool error. missing --network= parameter 

### ISSUE THREAD

**Issue by sean-morgan** [josenk/terraform-provider-esxi#7]
I'm trying to clone an ovf into esxi and getting 

> Error: Error applying plan:
> 
> 1 error(s) occurred:
> 
> * esxi_guest.vmtest: 1 error(s) occurred:
> 
> 2018/10/06 17:08:11 [DEBUG] plugin: waiting for all plugin processes to complete...
> * esxi_guest.vmtest: There was an ovftool Error:exit status 1

After setting TF_LOG=DEBUG I see

> 56238-guest-create.go:189: [guestCREATE] ovf_cmd: ovftool --acceptAllEulas --noSSLVerify --X:useMacNaming=false -dm=thin --name='vmtest' --overwrite -ds='datastore1' '/Users/morgan/Desktop/tinylinux.ovf' 'vi://root:<sanitized>@vhost2.home.lab/'

Running that from command line I get 

> Error: No network mapping specified. OVF networks:   External-VM-Network. Target networks:   Home  Host-only  Lab

If I run it adding --network="Lab" to the ovftool cmd line everything runs fine.

I was expecting the plugin to take the virtual_network specified in .tf to as the parameter.

**Comment by josenk** [comment]
Is tinylinux.ovf public available? (so I can try to re-create the issue)  Have you tried other sources (ovf or vmx) that work with your Lab network?
 
Can you upload your .tf file that has the network configuration...

**Comment by sean-morgan** [comment]
I grabbed the OVA for tinylinux from [VMware communities site](https://communities.vmware.com/servlet/JiveServlet/downloadBody/21621-102-3-28798/Tiny%20Linux%20VM.ova)


[main.tf.txt](https://github.com/josenk/terraform-provider-esxi/files/2453690/main.tf.txt) contains my .tf file (minus the .txt) extension.

I wasn't able to get anything to apply successfully via ovf but I did get a VM to clone successfully and had no problem getting a bare-metal guest.

**Comment by josenk** [comment]
Thanks for pointing this out.   I was able to recreate the problem.    I'll work on a fix.

**Comment by josenk** [comment]
Should be fixed in latest release (v1.1.1)

**Comment by sean-morgan** [comment]
Seems to work great for me on the test case. I'll advise if I run into any real-world problems.

Thanks for the quick fix.
