### ISSUE TITLE
Cant use the provider

### ISSUE THREAD

**Issue by ankycooper** [josenk/terraform-provider-esxi#70]
Hi I'm using the example "01 Simple Guest" with esxi6.7 on tf plan I get the following message.

Provider "esxi" planned an invalid value for
esxi_guest.vmtest01.virtual_disks: attribute representing a list of nested
blocks must be empty to indicate no blocks, not null.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by josenk** [comment]
There is two sets of examples based on the version of terraform (0.11.x and 0.12.x).   Make sure you are using the correct examples.

**Comment by ankycooper** [comment]
I'm using examples not examples-legacy as I have TF (0.12.x)

**Comment by josenk** [comment]
Make sure you are using terraform-provider-esxi v 1.5.0 or newer.  Support for Terraform 0.12 was added in 1.5.0.
