### ISSUE TITLE
Provider ESXi not run MacOS Mojave

### ISSUE THREAD

**Issue by matgil** [josenk/terraform-provider-esxi#71]
Hi,
I already successfully used ESXi provider in the past.

I try build provider and download with GitHub.
Terraform v0.12.9 and v0.12.8
OS: MacOS Mojave 10.14.6

`terraform init `
Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.esxi: version = "~> 1.5"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

`terraform apply`
Error: Failed to instantiate provider "esxi" to obtain schema: fork/exec /usr/local/bin/terraform-provider-esxi_v1.5.2: exec format error

**Comment by josenk** [comment]
I uploaded a mac version of the plugin.   After copying it to your path, rename it.  (remove the ".mac" extension)
>https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.5.2

**Comment by beamsoul** [comment]
> I uploaded a mac version of the plugin. After copying it to your path, rename it. (remove the ".mac" extension)
> 
> > https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.5.2

How to rename the mac extension?

**Comment by beamsoul** [comment]
> I uploaded a mac version of the plugin. After copying it to your path, rename it. (remove the ".mac" extension)
> 
> > https://github.com/josenk/terraform-provider-esxi/releases/tag/v1

Hello, I was using the 1.6 and i'm facing the exact issue... Could you help me
