### ISSUE TITLE
Unable to build terraform-provider-esxi

### ISSUE THREAD

**Issue by youvegotmoxie** [josenk/terraform-provider-esxi#74]
While following along with the build steps I'm encountering the following error:
```
go: github.com/josenk/terraform-provider-esxi@v1.5.2: parsing go.mod:
        module declares its path as: terraform-provider-esxi
                but was required as: github.com/josenk/terraform-provider-esxi
```
I found this [resource](https://github.com/golang/go/wiki/Modules#how-can-i-resolve-parsing-gomod-unexpected-module-path-and-error-loading-module-requirements-errors-caused-by-a-mismatch-between-import-paths-vs-declared-module-identity) and tried adding the full path of the module but it made no difference. Unfortunately I simply am not familiar enough with this language and and the how project directories need to be laid out to make much headway on this:
```
diff --git a/go.mod b/go.mod
index 78cbd52..aac2287 100644
--- a/go.mod
+++ b/go.mod
@@ -1,4 +1,4 @@
-module terraform-provider-esxi
+module github.com/josenk/terraform-provider-esxi

 require (
        github.com/hashicorp/terraform v0.12.2
@@ -7,3 +7,5 @@ require (
        github.com/tmc/scp v0.0.0-20170824174625-f7b48647feef
        golang.org/x/crypto v0.0.0-20190611184440-5c40567a22f8
 )
+
+go 1.13
```

Any assistance you could provide in debugging this would be appreciated.

**Comment by josenk** [comment]
You can download precompiled binaries here.

https://github.com/josenk/terraform-provider-esxi/releases

**Comment by youvegotmoxie** [comment]
Thanks, that works for me.

**Comment by youvegotmoxie** [comment]
I'm now encountering this issue: https://github.com/josenk/terraform-provider-esxi/issues/71

**Comment by josenk** [comment]
I uploaded a mac version of the plugin.   After copying it to your path, rename it.  (remove the ".mac" extension)
>https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.5.2

**Comment by beamsoul** [comment]
> Thanks, that works for me.
I'm facing the same issue, could you help me, if you solved your problem
