### ISSUE TITLE
cloud-init for ubuntu cloud image is not processed

### ISSUE THREAD

**Issue by Voronenko** [josenk/terraform-provider-esxi#76]
Good day,

 trying to use cloud-init enabled image https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.ova

Terraform snippet used:
```
  guestinfo = {
    "userdata.encoding" = "gzip+base64"
    "userdata"          = base64gzip(data.template_file.userdata_default.rendered)
  }

```

upon deployment, in VM parameters see

```
guestinfo.userdata = ....
guestinfo.userdata.encoding | gzip+base64
```
Decoding gives proper original cloud-config file

but cloud-config is not picked up - instance remains unconfigured
(Also tried the same cloud config with aws - provisions ok.)

Any hints on troubleshooting?  Or does it work wit coreos only ?

--

**Comment by Voronenko** [comment]
Following up processing OVF properties, btw I have better results (OVF properties overrides are accepted and processed by deployed instance), if I invoke following command

```
ovftool --acceptAllEulas --noSSLVerify --X:useMacNaming=false --X:injectOvfEnv --allowExtraConfig --prop:password=Passw0rd1 --powerOn --sourceType=OVA -dm=thin --name='vmtest' --overwrite -ds='ESXI'  --network='VM Network' '/home/slavko/personal/ESXI/bionic/bionic.ova' 'vi://root:PASSWORDCENSORED@esxi/'
```

i.e I've added.` --X:injectOvfEnv --allowExtraConfig --prop:password=Passw0rd1 --powerOn --sourceType=OVA`
to what is currently executed via provider

**Comment by Voronenko** [comment]
I have introduced +- naive but initially working support for deploying parametrized OVA images

https://github.com/josenk/terraform-provider-esxi/pull/78

**Comment by josenk** [comment]
Is this the only way this can be done?  Seems like many moving parts just to inject userdata.    I'm surprised that the currently solution doesn't work???   Did you review the cloud-init logs .

I'll review this more...

**Comment by Voronenko** [comment]
Perhaps answer is in exploring ova parameters for coreos ova image downloaded from

https://coreos.com/os/docs/latest/booting-on-vmware.html

```
ovftool  --hideEula coreos_production_vmware_ova.ova | more
```

as we see, "guestinfo" we see now in provider, looks like a specific naming convention set for 
ova parameters of this image, 

```
  Key:         guestinfo.coreos.config.data
  Label:       CoreOS config data
  Type:        string
  Description: Inline cloud-config data

  Key:         guestinfo.coreos.config.data.encoding
  Label:       CoreOS config data encoding
  Type:        string
  Description: Encoding for cloud-config data
```

while other ova images might have completely another naming convention for parameters, as was spotted, for example, with ubuntu cloud images.

Thus those parameters need to be generalized anyway.

**Comment by Voronenko** [comment]
I btw also tried just to inject properties into parameters without passing as ovftool parameters, as guestinfo does - those are rather not picked up. Only direct passing as parameters for ovftool helps so far.

![image](https://user-images.githubusercontent.com/701233/68018455-7be03d80-fc99-11e9-8e8b-c3d72d948ed0.png)

(I am at  6.7.0 (Build 8169922) )

**Comment by josenk** [comment]
That ubuntu cloud image doesn't support VMware...   The default install of cloud-init doesn't have the vmware plugin installed.     In the examples directory, I give you the web address to download the plugin.
>https://github.com/josenk/terraform-provider-esxi/blob/master/examples/05%20CloudInit%20and%20Templates/main.tf#L14-L23

There is a high compatibility with this plugin, but I cannot guarantee that any OVF/OVA/VMX downloaded will work perfectly.

I feel there are better solutions:
1) You can install it (without userdata), then install the vmware plugin, then repackage it or use it as a source vm.

2) You can also take a look at this thread for another work-around.  https://github.com/josenk/terraform-provider-esxi/issues/57


I'll take a look at your PR... But honestly, I really don't like the requirement to power-on the VM.   That will increase build-time by minutes!   You still have a requirement that the OVA/OVF requires cloud-init installed... (so far, those Ubuntu images are the only one I found).   Anyone using this method will need to increase the guest_startup_timeout.

**Comment by Voronenko** [comment]
@josenk   aha, I see. Although is official cloud image (regularly updated on /current) - i.e. something I expect to use "as is".

In deployed form, btw, image is shown in esx as one with installed open vmware tools of some version.

**Comment by josenk** [comment]
Merged your PR, did a few tweaks and improved documentation...    

Added support for ovf_properties in latest release.
>https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.6.0
