### ISSUE TITLE
VM and Disk creation on the same path

### ISSUE THREAD

**Issue by replay111** [josenk/terraform-provider-esxi#80]
Hi again ;-)

I wanted to create template vm and during that creation I want to have vm disks in the same folder as I have the whole VM (I am doing that using UI/Client). But during the try I faced two problems - one is related with cyclic dependencies:

```
Error: Cycle: esxi_guest.vm-template, esxi_virtual_disk.esxi_hdd
```

but this I solved (for now) in this way:

```
resource "esxi_guest" "vm-template" {
  guest_name = "vm-template"
  disk_store =  "${var.esxi_storage}"

  memsize  = "2048"
  numvcpus = "2"
  virthwver = "vmx-08"

  guestos = "centos-64"

  boot_disk_type = "thin"
  boot_disk_size = "20"

  power = "off"

  network_interfaces {
    virtual_network = "VM Network"
    nic_type        = "${var.esxi_network_interface_type}"
  }

  virtual_disks {
    virtual_disk_id = "${esxi_virtual_disk.esxi_hdd.id}"
    slot = "0:1"
  }

}

resource "esxi_virtual_disk" "esxi_hdd" {
  virtual_disk_disk_store = "${var.esxi_storage}"
  # virtual_disk_dir        = "${esxi_guest.vm-template.id}"
  virtual_disk_dir        = "vm-template"
  virtual_disk_name       = "hdd_01.vmdk"
  virtual_disk_size       = 30
  virtual_disk_type       = "eagerzeroedthick"
}
```

but then during ```terraform apply``` I am given error like this:
```
Error: Guest path already exists. fullPATH:"/vmfs/volumes/LOCAL_STORAGE/vm-template"


  on 10-template.tf line 2, in resource "esxi_guest" "vm-template":
   2: resource "esxi_guest" "vm-template" {
```

which is caused by assumption that if folder already exist than machine is already created and plugin ends with error - what can be seen in your [commit](https://github.com/josenk/terraform-provider-esxi/commit/a2e96ff707540b6db6f16bcaa956008510d8dfc1#diff-0d83a2a7db35e213e03be5489235da3aR79)

Maybe it would be better to also check (additional check) if vmx file exists - if yes then machine is created - but if not then we can create machine even if folder exists... I think...

**Comment by replay111** [comment]
Maybe something like this (sorry I am not GO Lang programmer):

```
remote_cmd_check_vmx = fmt.Sprintf("stat -t %s/%s.vmx", fullPATH)
stdout_check, _ = runRemoteSshCommand(esxiSSHinfo, remote_cmd_check_vmx, "check if guest path already exists.")


if ( (strings.Contains(stdout, "No such file or directory") == true) || (strings.Contains(stdout_check, "No such file or directory") == true) ) {
```

**Comment by josenk** [comment]
There is no bug.  This is by design.

   You are trying to create a guest in a certain path.  However, that filesystem path already exists (which is OK) and there is a guest.vmx file that exists (which is NOT OK)...

>https://github.com/josenk/terraform-provider-esxi/blob/a2e96ff707540b6db6f16bcaa956008510d8dfc1/esxi/guest-create.go#L66-L70

Clean up, or use a new path, then it should work.

**Comment by replay111** [comment]
First is disk created because I can see that on vSphereClient. The VMDK file there is correct. Then during creation of machine this error occurs which is in my opinion wrong as I do not have there any vmx files - only one created vmdk - which is ok for me.

**Comment by replay111** [comment]
I just try like this - by creating subfolder:

```
resource "esxi_virtual_disk" "esxi_hdd" {
  virtual_disk_disk_store = "${var.esxi_storage}"
  # virtual_disk_dir        = "${esxi_guest.vm-template.id}"
  virtual_disk_dir        = "vm-template/disks"
  virtual_disk_name       = "hdd_01.vmdk"
  virtual_disk_size       = "${var.esxi_default_disk_size}"
  virtual_disk_type       = "eagerzeroedthick"
}
```

but result is the same:
```
esxi_virtual_disk.esxi_hdd: Creating...
esxi_virtual_disk.esxi_hdd: Creation complete after 5s [id=/vmfs/volumes/LOCAL_STORAGE/vm-template/disks/hdd_01.vmdk]
esxi_guest.vm-template: Creating...

Error: Guest path already exists. fullPATH:"/vmfs/volumes/LOCAL_STORAGE/vm-template"


  on 10-template.tf line 2, in resource "esxi_guest" "vm-template":
   2: resource "esxi_guest" "vm-template" {
```

It looks like by design none files and folders can be inside of virtual machine directory... :(

**Comment by josenk** [comment]
subfolders are not supported.

**Comment by replay111** [comment]
that's fine, but creating vmdk file in the same folder as VM could work :D

**Comment by josenk** [comment]
You can have your virtual disks in the same directory if you like.   This works.
```
provider "esxi" {
  esxi_hostname = var.esxi_hostname
  esxi_hostport = var.esxi_hostport
  esxi_username = var.esxi_username
  esxi_password = var.esxi_password
}

variable "disk_store"    { default = "DS_3TB" }
variable "guest_name"    { default = "vm_test" }


#########################################
#  Virtual Disks
#########################################
resource "esxi_virtual_disk" "vdisk1" {
  virtual_disk_disk_store = var.disk_store
  virtual_disk_dir        = var.guest_name
  virtual_disk_name       = "${var.guest_name}-vdisk_1.vmdk"
  virtual_disk_size       = 10
}

#########################################
#  ESXI Guest resource
#########################################
#
resource "esxi_guest" "vmtest03" {
  guest_name = var.guest_name
  disk_store = var.disk_store

  clone_from_vm = "centos7"

  network_interfaces {
    virtual_network = "VM Network"
  }

  virtual_disks {
    virtual_disk_id = esxi_virtual_disk.vdisk1.id
    slot            = "0:1"
  }
}
```

**Comment by replay111** [comment]
Yeah, but this rely on already created template. I am trying to have this template machine configuration in terraform. For me this still does not work:

```
variable "guest_name"    { default = "vm_test" }

resource "esxi_virtual_disk" "esxi_hdd" {
  virtual_disk_disk_store = "${var.esxi_storage}"
  virtual_disk_dir        = "${var.guest_name}"
  virtual_disk_name       = "${var.guest_name}-hdd-01.vmdk"
  virtual_disk_size       = "${var.esxi_default_disk_size}"
  virtual_disk_type       = "eagerzeroedthick"
}


resource "esxi_guest" "template-node" {
  guest_name = "${var.guest_name}"
  disk_store =  "${var.esxi_storage}"

  memsize  = "2048"
  numvcpus = "2"
  virthwver = "vmx-08"

  guestos = "centos-64"

  power = "off"

  network_interfaces {
    virtual_network = "VM Network"
    nic_type        = "${var.esxi_network_interface_type}"
  }

  virtual_disks {
    virtual_disk_id = "${esxi_virtual_disk.esxi_hdd.id}"
    slot = "0:1"
  }

}
```

**Comment by josenk** [comment]
OK, you found another bug...  Builds with no source is very rarely used, so I was not paying attention to that detail.  If you update to the latest version, you should be OK.

>https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.5.4

**Comment by replay111** [comment]
Outstanding!
Only thing to remember is to name additional disk different than machine name ie:
```
vm_test_hdd02
```

otherwise error will appear again ;-)

Thank you! Case solved - I am closing it!
