### ISSUE TITLE
ovf_source as URL

### ISSUE THREAD

**Issue by replay111** [josenk/terraform-provider-esxi#83]
Hi ;-)

Is there any chance to support url links in ```ovf_source``` parameter?
I've checked that ovftool supports it:

```bash
ovftool -n=vmtest -ds=LOCAL_STORAGE http://nexus.domain.tld:8081/nexus/service/local/repositories/images/content/esxi/templates/centos7/1.0.0/centos7-1.0.0-x64.ova vi://root@my-esxi.domain.tld:443
```

and I am wonder if this can be also achieved in your plugin?

**Comment by silasb** [comment]
Have you tested this as `ovf_source`?  Based on the source code this should work as-is.

**Comment by silasb** [comment]
This assumes that `ovftool` will do the heavy lifting and pull down the image.

**Comment by replay111** [comment]
Yes I did the test - that is why I've raised this ticket. ovftool works out of the box but it didn't work for me with plugin:

```
Error: File not found: http://nexus.domain.tld:8081/nexus/service/local/repositories/images/content/esxi/templates/centos7/1.0.0/centos7-1.0.0-x64.ova

  on main.tf line 2, in resource "esxi_guest" "docker":
   2: resource "esxi_guest" "docker" {
```

maybe when you passing this source to ovftool you are adding protocol type by default like ```file://``` ?

**Comment by josenk** [comment]
There was a minor fix to get this going...   I think it's a great addition.
>https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.6.1

**Comment by replay111** [comment]
I looks like now I am able to create VM but for some reason ssh connection for remote-exec stopped working.... it looks like in this section:
```
  connection {
    host        = self.ip_address
    type        = "ssh"
    user        = var.vm_ssh_username
    password    = var.vm_ssh_password
  } 
```

this part ```host        = self.ip_address``` is not working anymore.... 
I am not sure if this is related.... but when I switched back to old plugin (1.6.0) everything works fine...
Also I did test with file located on local filesystem (on pc, not on esxi) and this new plugin also failed with obtaining host IP.

**Comment by josenk** [comment]
If you run "terraform refresh" does it get the IP?   If that's the case, you need to increase the guest_startup_timeout.

**Comment by replay111** [comment]
I am jumping int to loop in remote-exec as it is waiting for IP address to do ssh connection and as a result it fails after a large number of retries.
Previous version of plugin does not have such problems. IP is given immediately and ssh connection is successful.

**Comment by josenk** [comment]
Change the guest startup timeout.

**Comment by replay111** [comment]
Still it is not working like previous version. It takes a lot of time and not all remote-execs were given IP addresses....

**Comment by replay111** [comment]
Timeout was set to 180:

```
esxi_guest.master: Still creating... [4m21s elapsed]
esxi_guest.master (remote-exec): Connecting to remote host via SSH...
esxi_guest.master (remote-exec):   Host:
esxi_guest.master (remote-exec):   User: root
esxi_guest.master (remote-exec):   Password: true
esxi_guest.master (remote-exec):   Private key: false
esxi_guest.master (remote-exec):   Certificate: false
esxi_guest.master (remote-exec):   SSH Agent: true
esxi_guest.master (remote-exec):   Checking Host Key: false
esxi_guest.master: Still creating... [4m31s elapsed]
esxi_guest.master: Still creating... [4m41s elapsed]
esxi_guest.master (remote-exec): Connecting to remote host via SSH...
esxi_guest.master (remote-exec):   Host:
esxi_guest.master (remote-exec):   User: root
esxi_guest.master (remote-exec):   Password: true
esxi_guest.master (remote-exec):   Private key: false
esxi_guest.master (remote-exec):   Certificate: false
esxi_guest.master (remote-exec):   SSH Agent: true
esxi_guest.master (remote-exec):   Checking Host Key: false
esxi_guest.master: Still creating... [4m51s elapsed]
esxi_guest.master: Still creating... [5m1s elapsed]
esxi_guest.master (remote-exec): Connecting to remote host via SSH...
esxi_guest.master (remote-exec):   Host:
esxi_guest.master (remote-exec):   User: root
esxi_guest.master (remote-exec):   Password: true
esxi_guest.master (remote-exec):   Private key: false
esxi_guest.master (remote-exec):   Certificate: false
esxi_guest.master (remote-exec):   SSH Agent: true
esxi_guest.master (remote-exec):   Checking Host Key: false
esxi_guest.master: Still creating... [5m11s elapsed]
esxi_guest.master: Still creating... [5m21s elapsed]
esxi_guest.master (remote-exec): Connecting to remote host via SSH...
esxi_guest.master (remote-exec):   Host:
esxi_guest.master (remote-exec):   User: root
esxi_guest.master (remote-exec):   Password: true
esxi_guest.master (remote-exec):   Private key: false
esxi_guest.master (remote-exec):   Certificate: false
esxi_guest.master (remote-exec):   SSH Agent: true
esxi_guest.master (remote-exec):   Checking Host Key: false
esxi_guest.master: Still creating... [5m31s elapsed]
```

**Comment by josenk** [comment]
Please update this thread with your main.tf (or relevant terraform files).   I want to re-create your problem...

Have you looks at the code diffs???  There is NO code changes in the detection of the IP address. Actually, that function hasn't changed in the past year.
>https://github.com/josenk/terraform-provider-esxi/commit/9242a422f3f985f8c0c2738568d9836894e46ef0

>https://github.com/josenk/terraform-provider-esxi/blame/master/esxi/guest_functions.go#L452-L504

**Comment by replay111** [comment]
Hi,

yes - I was checking that commit - that is why I am totally confused... 

My sources are here: https://github.com/replay111/tf-esxi-test

For 1.6.0 I am just changing path from Nexus to some local dir - this is only one difference.

**Comment by josenk** [comment]
Does the scripts in /root/install/ change anything for networking,  like setting a static ip?   Or please update your repo with its source code.

**Comment by replay111** [comment]
Yes it does - you can see body here: https://github.com/josenk/terraform-provider-esxi/issues/14#issuecomment-559586283

**Comment by replay111** [comment]
But still it is not called with 1.6.1 as terraform is not able to ssh to up and running host to change this IP because of this loop:

```
esxi_guest.master (remote-exec): Connecting to remote host via SSH...
esxi_guest.master (remote-exec):   Host:
esxi_guest.master (remote-exec):   User: root
esxi_guest.master (remote-exec):   Password: true
esxi_guest.master (remote-exec):   Private key: false
esxi_guest.master (remote-exec):   Certificate: false
esxi_guest.master (remote-exec):   SSH Agent: true
esxi_guest.master (remote-exec):   Checking Host Key: false
```

**Comment by josenk** [comment]
Sorry,  I  don't support you changing the ip.  You can refer to a separate repo for ideas and if you like you can contribute your solution if you get it working... 

https://github.com/josenk/terraform-provider-esxi-wiki

**Comment by replay111** [comment]
But it doesn't matter if I use this script or not. In remote exec I can have ```ls -la``` and output is the same.  This is not about what my script is doing, but about using remote-exec afer last update.
