### ISSUE TITLE
terraform apply and parallelism with remote-exec

### ISSUE THREAD

**Issue by replay111** [josenk/terraform-provider-esxi#85]
Hi,
I've found that this is not working:

```
  provisioner "remote-exec" {
    inline = [
      "/root/install/hostname.sh gitlab",
      "screen -AmdS delay_ip_change bash",
      "screen -S delay_ip_change -p 0 -X stuff $'sleep 20s\n/root/install/network.sh 21\r'"
    ]
  }
```

when I am running ```terraform apply``` (with default options), 

but when I use ```terraform apply -parallelism 1``` then everything works ok.

Is there any limitation with that provisioner?

**Comment by replay111** [comment]
I've extended the delay and set it different for each hosts, but I think that should just with the same values....

**Comment by josenk** [comment]
This github repo is for a provider plugin, not a provisioner...   If you feel you have a bug with a provisioner,  you need to open an issue there.

**Comment by replay111** [comment]
OK I thought that this can be caused by the ESXi and the communication that is provided by plugin, but if this is not related then I will close this and search in terraform pages/wiki.
