### ISSUE TITLE
Unable to assign Static IP

### ISSUE THREAD

**Issue by vikas-nyt** [josenk/terraform-provider-esxi#87]
Hi Josenk,

Your article helped me to create and deploy VM without vcenter.Thanks
https://github.com/josenk/terraform-provider-esxi.
Could you please advise on assigning a static ip address and DNS to deployed VM in main.tf file.
I am unable to figure it out .
Thanks ,
Vikas.K.S

**Comment by josenk** [comment]
https://github.com/josenk/terraform-provider-esxi-wiki
