### ISSUE TITLE
building the provider failed

### ISSUE THREAD

**Issue by aracloud** [josenk/terraform-provider-esxi#88]
I tried build the provider with:

cd $GOPATH/src/github.com/josenk/terraform-provider-esxi
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-w -extldflags "-static"' -o terraform-provider-esxi_`cat version`

But I got: 
$ CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-w -extldflags "-static"' -o terraform-provider-esxi_`cat version`
go: github.com/josenk/terraform-provider-esxi@v1.6.1: parsing go.mod:
	module declares its path as: terraform-provider-esxi
	        but was required as: github.com/josenk/terraform-provider-esxi

Then:
$ cat go.mod 
module terraform-provider-esxi

require (
	github.com/hashicorp/terraform v0.12.2
	github.com/josenk/terraform-provider-esxi v1.6.1
	github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51 // indirect
	github.com/tmc/scp v0.0.0-20170824174625-f7b48647feef
	golang.org/x/crypto v0.0.0-20190611184440-5c40567a22f8
)

go 1.13

What is wrong here?

**Comment by josenk** [comment]
You can download compiled binaries here:
>https://github.com/josenk/terraform-provider-esxi/releases

**Comment by klamontagne-om** [comment]
I am also on Go 1.13 and getting this error, my coworker on 1.12 was able to compile without issues though

**Comment by josenk** [comment]
Looks like they changed things a little in 1.13...    Google shows many others with similar error messages.  (other modules of course)

I think I found a work-around to make it compile.  Replace the contents of go.mod with the following.  Can you give it a try and let me know...

```
module github.com/josenk/terraform-provider-esxi

require (
	github.com/hashicorp/terraform v0.12.2
	github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51 // indirect
	github.com/tmc/scp v0.0.0-20170824174625-f7b48647feef
	golang.org/x/crypto v0.0.0-20190611184440-5c40567a22f8
)
```

**Comment by josenk** [comment]
If you are interested, please try v1.6.2.
> https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.6.2
