### ISSUE TITLE
MAIN setting

### ISSUE THREAD

**Issue by felipeaom** [josenk/terraform-provider-esxi#89]
Good afternoon, I'm using your plugin to use Terraform on my ESXi 6.7 Server. When I create a VM through terraform its compatibility is made by version 5.0 and the network card does not work. Is it possible to change compatibility to start on ESXi 6.7?

**Comment by josenk** [comment]
Yes, you can change the virtual hardware version by using the following configuration option...   BTW:  It's documented in the README.md

  * virthwver - Optional - esxi guest virtual HW version. See esxi documentation for compatible values. - Default 8 or taken from cloned source.
