### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by felipeaom** [josenk/terraform-provider-esxi#91]
Good afternoon, I have an ESXi 6.7 and I am setting up my Terraform to use its plugin. But when I create a VM via mail.tf it comes with ESXi 5.0 compatibility. Do you know which parameter I can use to change this version? And choosing a GUEST, do you have any idea of a list of systems to use in main?

**Comment by josenk** [comment]
Are you reporting an Issue or bug?

**Comment by felipeaom** [comment]
I believe it is a bug. I looked for some parameter to change VM build compatibility and didn't find it. Do you know if it is possible to configure in main.tf to get the latest compatibility?

**Comment by josenk** [comment]
Yes, you can change the virtual hardware version by using the following configuration option... BTW: It's documented in the README.md

    virthwver - Optional - esxi guest virtual HW version. See esxi documentation for compatible values. - Default 8 or taken from cloned source.
