### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by felipeaom** [josenk/terraform-provider-esxi#92]
Good afternoon, I have an ESXi 6.7 to use the unformed terraform plugin. But all the virtual machines I create get ESXi Compatibility 5.0, how to fix or configure in main.tf?

![image](https://user-images.githubusercontent.com/38219720/71120939-249c1b00-21bc-11ea-844c-6d4b5ad481c5.png)

**Comment by josenk** [comment]
This is the LAST time I will write the same thing...  For something that is SIMPLE and CLEARLY DOCUMENTED, you opened 3 issues for the exact same thing.

   ---->>>  If you open another issue, I will BAN you  <<<------

---
Yes, you can change the virtual hardware version by using the following configuration option... 

    virthwver - Optional - esxi guest virtual HW version. See esxi documentation for compatible values. - Default 8 or taken from cloned source.
