### ISSUE TITLE
username and password is shown on logs in plaintext

### ISSUE THREAD

**Issue by JouniRajalaComiq** [josenk/terraform-provider-esxi#96]
Username and password is shown in logs in plain text

`2020-02-05T08:26:21.802+0200 [DEBUG] plugin.terraform-provider-esxi_v1.6.2: pid-31779-guest-create.go:286: [guestCREATE] ovf_cmd: ovftool --acceptAllEulas --noSSLVerify --X:useMacNaming=false  -dm=thin --name='vm1' --overwrite -ds='datastore1'  --network='VM Network' '/ubuntu1804.ovf' 'vi://USERNAME:PASSWORD@192.168.0.2/'`

Credentials should be masked out in log files.

**Comment by josenk** [comment]
Fixed in v1.6.3.
>https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.6.3
