### ISSUE TITLE
Need to be able to set parameter 'disk.enableUUID=TRUE'

### ISSUE THREAD

**Issue by JouniRajalaComiq** [josenk/terraform-provider-esxi#97]
Need way to set parameter disk.enableUUID as described in document https://kb.vmware.com/s/article/52815

Now I need to do this manually for all VM's

**Comment by topikettunen** [comment]
Solved in #98

**Comment by josenk** [comment]
It's now default in v1.6.3.
>https://github.com/josenk/terraform-provider-esxi/releases/tag/v1.6.3
